### ISSUE TITLE
Beta approximation fails to converge regularly

### ISSUE THREAD

**Issue by GlastonburyC** [broadinstitute/tensorqtl#1]
Everytime I have ran permutations to determine cis or trans-eQTL significance I get the following Warning:
```
WARNING: scipy.optimize.newton failed to converge (running scipy.optimize.minimize)
/usr/local/lib/python3.6/dist-packages/tensorqtl/tensorqtl.py:210: RuntimeWarning: invalid value encountered in sqrt
  return 2*stats.t.cdf(-np.abs(np.sqrt(tstat2)), dof)
/usr/local/lib/python3.6/dist-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/usr/local/lib/python3.6/dist-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/usr/local/lib/python3.6/dist-packages/scipy/stats/_distn_infrastructure.py:1738: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0
```

Is it possible to increase or set as an argument the number of iterations to pass to `scipy.optimize.minimize`?

**Comment by francois-a** [comment]
This error is usually triggered when the initial value of `dof` is too far off. Are you able to provide a simple example that reproduces this error?

**Comment by GlastonburyC** [comment]
Could it be possibly caused by using multiple tissues from the same individual?

**Comment by francois-a** [comment]
I'm not sure, although that's something you probably should avoid without changing the model to account for this. How many samples and individuals are in your dataset?

**Comment by francois-a** [comment]
Hi @GlastonburyC, were you able to sort this out?
