### ISSUE TITLE
No pval_nominal_threshold output from cis.map_cis()

### ISSUE THREAD

**Issue by cldebban** [broadinstitute/tensorqtl#100]
I've been working on setting up my project to run with tensorQTL, but when I run the cis.map_cis() function to get cisQTLs with permutations, the pval_nominal_threshold column is missing from the results. Is there an argument I'm missing that would let me get this output?

The code I'm using is based on the example:

cis_df = cis.map_cis(genotype_df, variant_df, 
                     phenotype_df.loc[phenotype_pos_df['chr']==f'chr{i}'],
                     phenotype_pos_df.loc[phenotype_pos_df['chr']==f'chr{i}'],
                     covariates_df=covariates_df, seed=123456)

Thanks,
Catherine

**Comment by francois-a** [comment]
Hi, you need to call `post.calculate_qvalues` on the output (`cis_df`). I've updated the [example](https://github.com/broadinstitute/tensorqtl/blob/master/example/tensorqtl_examples.ipynb) accordingly.

**Comment by cldebban** [comment]
Excellent, thank you! To clarify your comment in the example: "in practice, this must be run on all genes, not a subset", do you mean that if I calculate cis-QTLs separately for each chromosome (my genotype files are large so I was planning on this), I should combine the output datasets before computing q-values?

Also, I'm doing this for a pQTL project where I'm combining datasets from different versions of Somascan that check expression on different numbers of proteins (~1100, 1300, 5000, and 7000). Since this created large chunks of NA's in the full dataset, I was getting "All correlations resulted in NaN" errors like in [issue #55.](https://github.com/broadinstitute/tensorqtl/issues/55) Because of this, I split the dataset into chunks without NA's to run tensorQTL (i.e. for the ~2000 proteins only tested in the 7k version, I made a chunk that only included those individuals run with 7k, and for the ~1000 proteins tested in all versions I included all individuals in that chunk). Should I calculate q-values within chunks or combine everything before doing that? Does it matter? I haven't worked with permutations before so I'm still working on wrapping my head around the math of it.

Thanks!

**Comment by francois-a** [comment]
Yes, q-values should be computed across all phenotypes tested (otherwise, this wouldn't properly correct for multiple hypotheses). In the CLI, there is now a `--chunk_size` option that allows loading genotypes in chunks for large datasets.

For mapping, the procedure you describe makes sense — the associations should be computed using only the samples available for each protein (in scenarios where there are fewer missing values, e.g., due to detection limits, imputation can be preferable).

**Comment by zhangpicb** [comment]
> Hi, you need to call `post.calculate_qvalues` on the output (`cis_df`). I've updated the [example](https://github.com/broadinstitute/tensorqtl/blob/master/example/tensorqtl_examples.ipynb) accordingly.

Dear @francois-a 

How to use post.calculate_qvalues in shell ?

Thanks in advanced!

**Comment by francois-a** [comment]
In the shell this function is automatically called where needed (in `cis` mode).
