### ISSUE TITLE
Clarification for the transformation procedure.

### ISSUE THREAD

**Issue by AlexSimis** [broadinstitute/tensorqtl#103]
Greetings!

Great work on both the tool and its documentation! I was wondering, whether I should input the transformed values (based on Inverse Normal Transformation) of my molecular trait (that is protein levels) or just the QCed values. Does the pipeline automatically transform the inputted phenotype values prior to QTL mapping? 

Thanks,
Alex.

**Comment by francois-a** [comment]
Hi,
Thanks! The phenotypes are not modified, so you'll need to apply the appropriate transformations (e.g., between-sample normalization, INT) beforehand.
