### ISSUE TITLE
QTL interaction error

### ISSUE THREAD

**Issue by yrjia1015** [broadinstitute/tensorqtl#104]
Hi, when running the 'cis QTL mapping: interactions' mode of Tensorqtl, the following error will occur during the runtime, and cannot be resolved after trying multiple solutions. Could you please help to see what caused it:

* 384 samples
  * 5391 phenotypes
  * 7064078 variants
  * including 1 interaction term(s)
    * using 0.05 MAF threshold
  * cis-window: ±1,000,000
  * checking phenotypes: 5391/5391
    ** dropping 34 phenotypes without variants in cis-window
  * Computing associations
    Mapping chromosome 1
    processing phenotype 8/5357 Traceback (most recent call last):File "/home/lib/python3.9/site-packages/tensorqtl/cis.py", line 306, in map_nominal
    ix = np.nanargmax(np.abs(tstat[:,1+ni:]).max(1))  # top association among all interactions tested
  File "/home/lib/python3.9/site-packages/numpy/lib/nanfunctions.py", line 613, in nanargmax
    raise ValueError("All-NaN slice encountered")
ValueError: All-NaN slice encountered

**Comment by curryfly5** [comment]
Hi,have you solved this problem?I had met the same problem while running 'cis QTL mapping: interactions'
