### ISSUE TITLE
Is TensorQTL computing a robust linear regression?

### ISSUE THREAD

**Issue by ariadnacilleros** [broadinstitute/tensorqtl#108]
Hi!

Thank you so much for TensorQTL software, it is really nice and efficient tool! I would like to ask if the computation of the cis-QTLs is a robust linear regression, or otherwise it is a simple linear regression such as MatrixQTL. Thank you so much in advance!

Best, 

Ariadna

**Comment by francois-a** [comment]
Hi, the model is the same as in MatrixEQTL/FastQTL.

**Comment by ariadnacilleros** [comment]
Hi, thank you so much for the answer!
