### ISSUE TITLE
how to get the beta value with cis_nominal mode

### ISSUE THREAD

**Issue by zhoudreames** [broadinstitute/tensorqtl#111]
This my code:
```
python3 -m tensorqtl ${plink_prefix} ${expression_bed} ${output} \
            --covariates ${covariates_file} \
                --mode cis_nominal
```
The output:
![image](https://github.com/broadinstitute/tensorqtl/assets/54714639/d09d4453-a84d-4914-8406-9b8699841bda)
But eQTL results do not have a beta value, how to add it ？ Thanks~

**Comment by zhoudreames** [comment]
@dinvlad @coreone @tfhartmann @davidbernick  I am so sorry to disturb you, can you help me?

**Comment by francois-a** [comment]
The beta value is in the `slope` column, please see [here](https://github.com/broadinstitute/tensorqtl/blob/master/docs/outputs.md).

**Comment by zhoudreames** [comment]
> The beta value is in the `slope` column, please see [here](https://github.com/broadinstitute/tensorqtl/blob/master/docs/outputs.md).

Thanks~
