### ISSUE TITLE
error of calculate_qvalues in post.py?

### ISSUE THREAD

**Issue by lushjia** [broadinstitute/tensorqtl#113]
It seems that the line 59 and line 61 of the funciton **calculate_qvalues** in **post.py** should be 
lb = lb.values[-1]
ub = ub.values[0]
Because the original command in the file, lb = lb[-1] would get value of index -1 but not the last item of the sorted pandas series. So does ub = ub[0].

**Comment by francois-a** [comment]
Thanks for pointing this out, this is due to a change in pandas behavior. Fixed in 70873a09e9cdd37223c8a82c158f10589fccd255.
