### ISSUE TITLE
[help] genotype format

### ISSUE THREAD

**Issue by CuteGold0407** [broadinstitute/tensorqtl#116]
Hi,
thank you for share this efficient tool, there is a little question about genotype
Is it necessary for the FORMAT field of a genotype to include DS?

**Comment by francois-a** [comment]
No, by default the GT field is used. If you want to use DS, you need to provide the `--dosages` flag.

**Comment by CuteGold0407** [comment]
Thank you! I fixed that，but there is another new problem, when i followed the tensorqtl_examples.ipynb and ran the cis mode. But some output files didn't contain the qval_thresshold column. In fact, I seperate the phenotype file by chr and run it in shell ,like:
for i in $(seq 1 22);
do
  python3 -m tensorqtl \
                ${pro}.genotype \
                ${path}/phenotype/chr${i}.bed.gz \
                permutate_PEER${peer}_chr${i} \
                --covariates covariates.txt \
                --mode cis \
                --window 100000 \
                --permutations 10000
done
and only output file for chr2 and chr21 didn't have the qval_thresshold column. in another project, it's chr9 and chr13

**Comment by CuteGold0407** [comment]
and then I ran the code only for chr2，the output still didn't have the qval_thresshold column. I also tried :
"
cis_df = cis.map_cis(genotype_df, variant_df, phenotype_chr2_df, phenotype_chr2_pos_df, covariates_df, window=100000, nperm=10000)
cis_dff = post.calculate_qvalues(cis_df, fdr=0.05, qvalue_lambda=0.85)
"
in python, it didn't work.

**Comment by francois-a** [comment]
Please open new issues for different problems. This seems to be the same as https://github.com/broadinstitute/tensorqtl/issues/80.
