### ISSUE TITLE
Negative af in output files

### ISSUE THREAD

**Issue by maxozo** [broadinstitute/tensorqtl#119]
Hi, Would you have any idea why i am getting negative allele frequency (af column) - do you know why or what does it mean?
![image (1)](https://github.com/broadinstitute/tensorqtl/assets/22347136/33fcc852-686d-4931-93c4-f8f608c47e5d)

Thanks,

**Comment by francois-a** [comment]
This might be because of missing values that are not (properly) imputed. Can you provide more details about the format of your genotypes?

**Comment by maxozo** [comment]
My genotypes are in plink pgen,sam,pvar format. 
Taking the particular vatiant interval composition Interval_202833 and chr22:18071577 i do not see anything unexpected in the files. 
The expression values for this interval are:

**Comment by francois-a** [comment]
Do you mind sending the expression and plink files for this example so I can try to reproduce the issue?

**Comment by maxozo** [comment]
Unfortunately no, this data can not be shared due to restrictions in place.Bw,Matiss Sent from my iPhoneOn 17 Jan 2024, at 17:50, François Aguet ***@***.***> wrote:﻿
Do you mind sending the expression and plink files for this example so I can try to reproduce the issue?

**Comment by francois-a** [comment]
Could you at least provide a minimally reproducible example like the data you posted above (as input files)?

**Comment by maxozo** [comment]
@francois-a that would take me a while to figure out. However i've been looking into this and it seems to be specific to the version 1.0.7 and doesnt seem to occur in the 1.0.9. 
This part in the code generates genotypes with negative values
`for k, (phenotype, genotypes, genotype_range, phenotype_id) in enumerate(igc.generate_data(chrom=chrom, verbose=verbose), k+1)`
, which eventually result in negative af's. 
Did anyone report this issue or a simmilar one before? Since ive been using tensorqtl on number of project I am woundering whether changing now to version 1.0.9 will change results a lot?

**Comment by francois-a** [comment]
There haven't been any changes that would easily explain this, and the outputs are consistent between versions in unit tests. Without a reproducible example it's difficult to diagnose the issue. The code you posted is the main loop where the associations are computed.
