### ISSUE TITLE
Warning and Error in tensorQTL trans mode

### ISSUE THREAD

**Issue by hnaeem** [broadinstitute/tensorqtl#123]
Dear, 

TensorQTL in trans mode (tran-eQTL) displays the following error message at the Terminal window. It also shows the warning: " 'rfunc' cannot be imported. R and the 'rpy2' Python package are needed", despite both the R and rpy2 packages being available on the HPC.
Any advice will be appreciated
Thank you.

**Warning: 'rfunc' cannot be imported. R and the 'rpy2' Python package are needed.**
[Feb 26 15:32:26] Running TensorQTL: trans-QTL mapping
  * WARNING: using CPU!
  * reading phenotypes (/gpfs/projects/SDR_transcriptomics_ymokrab/collaborate/khalid_lab/qgp_mitchondrial_proj/eQTL_analysis/genes/QTL/trans_qtl/2_transQTL/input/MT_gene_expression_inv_transform_fastqtl.bed.gz)
  * reading covariates (/gpfs/projects/SDR_transcriptomics_ymokrab/collaborate/khalid_lab/qgp_mitchondrial_proj/eQTL_analysis/genes/QTL/trans_qtl/2_transQTL/input/covariates_MT.txt.gz)
Mapping files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  3.09it/s]
/gpfs/software/genomics/tensorqtl/venv/lib/python3.6/site-packages/tensorqtl/genotypeio.py:145: PerformanceWarning: Slicing with an out-of-order index is generating 306 times more chunks
  self.bed = self.bed[:,ix]
  * p-value threshold: 1e-05
trans-QTL mapping
  * 1882 samples
  * 37 phenotypes
  * 50 covariates
/gpfs/software/genomics/tensorqtl/venv/lib/python3.6/site-packages/tensorqtl/core.py:52: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:1937.)
  self.Q_t, _ = torch.qr(C_t - C_t.mean(0))
  * 342578 variants
    processing batch 18/18
    elapsed time: 0.11 min
  * 342578 variants passed MAF >= 0.01 filtering
done.
  * filtering out cis-QTLs (within +/-5Mb)
  * writing output
[Feb 26 15:37:22] Finished mapping
Traceback (most recent call last):
  File "/gpfs/software/genomics/tensorqtl/venv/bin/tensorqtl", line 8, in <module>
    sys.exit(__main__())
**TypeError: 'module' object is not callable**

**Comment by hnaeem** [comment]
there has been no response regarding the error

**Comment by hnaeem** [comment]
Thank you for your message. 
All the TensorQTL, R, and rpy2 packages are available on the HPC where I am running the script. Here is the command for running TensorQTL in trans mode. I am getting the expected outcome (a log file and a txt.gz file containing trans-QTL results).

**Submitting the jobs per chromosome on LSF**

for chr in {1..22}; do 
    echo "tensorqtl ${plink_prefix_path}_chr_${chr} ${bed} ${prefix}_${chr} --mode trans --covariates ${cov} --maf_threshold 0.01 --output_text --output_dir $path/output/tensorqtl --return_r2" |bsub -q bionanoNFS -n 32 -P tensorqtl -J tensorqtl -e $path/log/tensorqtl.${chr}.e -o $path/log/tensorqtl.${chr}.o
done

**Comment by hnaeem** [comment]
I am receiving the anticipated outcome (a log file and a txt.gz file containing trans-QTL results). Can I rely on the output despite the error message mentioned above?

**Comment by francois-a** [comment]
In principle yes. Please update tensorQTL to the latest version, the torch.qr warning was resolved a while ago.

**Comment by hnaeem** [comment]
Dear @francois-a, Thank you for your message. I will install the latest version of the tool and let you know if there are any issues. Thank you.

**Comment by hnaeem** [comment]
Is this the updated version : [v1.0.9](https://github.com/broadinstitute/tensorqtl/releases/tag/v1.0.9)?

**Comment by lintingyi2014** [comment]
Hey hnaeem, 
I used to have this error too, the hpc we use installs tensorqtls as singularities on the hpc but the dependencies are needed separately. The singularities does not access the hpc's packages (rpy2). I suggest that you contact your institution's IT office.

**Comment by lintingyi2014** [comment]
Also, try --partition=gpu to allocate gpu
