### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'T' tensorqtl

### ISSUE THREAD

**Issue by lintingyi2014** [broadinstitute/tensorqtl#126]
AttributeError: 'dict' object has no attribute 'T' tensorqtl

Mapping files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:15<00:00,  5.02s/it]
trans-QTL mapping
  * 776 samples
  * 26083 phenotypes
  * 21 covariates
  * 9362705 variants
    processing batch 937/937
    elapsed time: 1.02 min
  * 6044095 variants passed MAF >= 0.05 filtering
done.
Traceback (most recent call last):
  File "/vf/users/HumanRNAProject/TYL/QTL/eQTL_broads/FULL/tensorqtl_examples.py", line 78, in <module>
    trans_df = trans.filter_cis(trans_df, phenotype_pos_df.T.to_dict(), variant_df, window=5000000)
  File "/usr/local/lib/python3.10/dist-packages/tensorqtl/trans.py", line 42, in filter_cis
    pos_dict = phenotype_pos_df.T.to_dict()

**Comment by francois-a** [comment]
The `trans.filter_cis` call changed:
```
trans_df = trans.filter_cis(trans_df, phenotype_pos_df, variant_df, window=5000000)
```
Please also see the [examples](https://github.com/broadinstitute/tensorqtl/blob/master/example/tensorqtl_examples.ipynb).

**Comment by lintingyi2014** [comment]
solved thank you
