### ISSUE TITLE
[Susie] ValueError: prior variance must be non-negative

### ISSUE THREAD

**Issue by lintingyi2014** [broadinstitute/tensorqtl#132]
please help me fix this

SuSiE fine-mapping
  * 734 samples
  * 22156 phenotypes
  * 69 covariates
  * 8526609 variants
  * cis-window: ±1,000,000
  * applying in-sample MAF >= 0.01 filter
  * checking phenotypes: 22156/22156
    ** dropping 37 phenotypes without variants in cis-window
  * fine-mapping
    processing phenotype 8/22119Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/tensorqtl/susie.py", line 705, in map
    res = susie(genotypes_res_t.T, phenotype_res_t.T, L=L,
  File "/usr/local/lib/python3.10/dist-packages/tensorqtl/susie.py", line 495, in susie
    s = init_finalize(s)
  File "/usr/local/lib/python3.10/dist-packages/tensorqtl/susie.py", line 99, in init_finalize
    raise ValueError("prior variance must be non-negative")
ValueError: prior variance must be non-negative

**Comment by francois-a** [comment]
Can you please provide an example dataset that reproduces this issue?

**Comment by lintingyi2014** [comment]
May I send it to you in private?

**Comment by francois-a** [comment]
Sure, no problem.

**Comment by lintingyi2014** [comment]
sorry was a problem on my end! It is solved now. 

Thanks!
