### ISSUE TITLE
[map_trans] R2 not returned in interaction analysis

### ISSUE THREAD

**Issue by lintingyi2014** [broadinstitute/tensorqtl#134]
[map_trans] R2 not returned in interaction analysis
I am not able to perform the following without R2 map permutations, apply permutations and calculate qvalues

>>> trans_df_age = trans.map_trans(
    genotype_df, phenotype_df, covariates_df=covariates_i_df,
    interaction_s=interaction_age_series,  # Use the series here
    batch_size=32, return_sparse=True, return_r2=True,
    pval_threshold=1e-5, maf_threshold=0.01
)
trans-QTL mapping
  * 731 samples
  * 22156 phenotypes
  * 68 covariates
  * 8526609 variants
  * including interaction term
/usr/local/lib/python3.10/dist-packages/tensorqtl/trans.py:188: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  interaction_mask_t = torch.BoolTensor(mask_s).to(device)
    processing batch 266457/266457
    time elapsed: 126.31 min
>>> print(trans_df_age)
               variant_id     phenotype_id        pval_g    pval_i       pval_gi        af
0            1:758443:G:C  ENSG00000088280  1.644766e-08  0.223717  4.616627e-08  0.135431
1            1:758443:G:C  ENSG00000148704  6.579484e-07  0.433384  2.150914e-06  0.135431
2            1:769257:G:A  ENSG00000112159  1.568243e-06  0.065019  6.012341e-06  0.038304
3            1:788511:C:G  ENSG00000213588  2.434556e-05  0.081816  9.844050e-06  0.018468
4            1:794299:G:C  ENSG00000088280  6.869206e-07  0.341993  4.500554e-07  0.174419
...                   ...              ...           ...       ...           ...       ...
3764757   X:155435125:C:T  ENSG00000083812  3.546907e-06  0.000033  2.072290e-06  0.031464
3764758  X:155526102:T:TG  ENSG00000087448  2.040481e-06  0.164254  2.746568e-06  0.032832
3764759   X:155616644:T:C  ENSG00000214820  3.228542e-05  0.928215  9.967886e-06  0.031464
3764760   X:155616644:T:C  ENSG00000204611  1.265706e-05  0.003505  5.902228e-06  0.031464
3764761   X:155616644:T:C  ENSG00000083812  3.547050e-06  0.000033  2.072370e-06  0.031464

[3764762 rows x 6 columns]
>>>

**Comment by francois-a** [comment]
Similar to cis-QTLs, permutations are not compatible with interactions for trans-QTLs.

**Comment by lintingyi2014** [comment]
Got it, thank you!
