### ISSUE TITLE
Which beta coresponds to which allele in the outputs? 

### ISSUE THREAD

**Issue by maxozo** [broadinstitute/tensorqtl#137]
Hi,
In our QTL analysis using TensorQTL, the SNP identifier format in the results is "chr:pos:A1:A2" where A1 and A2 represent alleles that come from the vcf file. We converted VCF files to PLINK format using PLINK2 and used these genotypes in TensorQTL. Based on the SNP identifier format and the PLINK conversion process, we presume that the order of alleles in the PLINK files corresponds to the order in the output eQTL results.

Could you kindly confirm whether the effect allele in TensorQTL analysis corresponds to A2 in the SNP identifier, considering that A1 is typically the reference allele in PLINK files generated from VCF data? We need to be sure which beta correspons to which allele in the outputs - https://github.com/broadinstitute/tensorqtl/blob/master/docs/outputs.md 

Thank you,
Best wishes,
Matiss

**Comment by jcgrenier** [comment]
This was answered in this issue I think. I was looking for the same thing in the manual.

[https://github.com/broadinstitute/tensorqtl/issues/88](https://github.com/broadinstitute/tensorqtl/issues/88)

Hope this helps!

**Comment by jcgrenier** [comment]
I would say that it's not that clear anyway for me. I'm using the plink option "--real-ref-alleles" from the moment I'm converting from a VCF file, so the alternative allele always stays A2. In my output, I have allele frequencies that are over 0.5. So, the what does the beta means here? Does the minor allele considered or it's the actual A1/A2 encoding of the input file that is considered?
Thanks a lot!

**Comment by francois-a** [comment]
Yes, @maxozo's description is correct (i.e., it is assumed that A1 is REF and A2 is ALT). The allele frequencies reported by TensorQTL are alternate allele frequencies, not minor allele frequencies, and hence can be >0.5 (this was done to facilitate identification of cases where ALT is not the minor allele).

**Comment by jcgrenier** [comment]
Sorry @francois-a to reopen this case. But how is the slope computed in the case of an alternate allele frequency above 0.5? I have a case where I'm comparing GTEx slope to my slope. GTEx is reporting on their side the MAF (0.17 in that case) and I'm using an encoding with the alternative allele frequency (AF of 0.82) and the slopes are both negative. Should I consider that the slope is computed using the minor/major definitions and not ref/alt? 
Thanks a lot for the clarification.

**Comment by jcgrenier** [comment]
Hello @francois-a , thanks for your reply! 
I just compared the same variant-gene association between the version that I was using previously (which was the v8) and the new v10. The slope have the same directions, but the maf is reported in this one, which was a bit confusing in the end. This new version reassures us! So I suppose the effect allele that is reported is the ALT in the end, even if the MAF is in the output file instead of the AAF.

**Comment by francois-a** [comment]
Where are you seeing MAFs in V10? All of the files should contain AF instead of MAF.

**Comment by jcgrenier** [comment]
Sorry, I meant that it was the AF in v10 and MAF in v8. But in the end the slopes are identical, so the effect allele is the ALT in both cases.

Thanks!

**Comment by francois-a** [comment]
I see, thanks for clarifying!
