### ISSUE TITLE
Errors in the BackgroundGenerator cause main thread to get stuck

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/tensorqtl#139]
Description
---

When an exception occurs in a `BackgroundGenerator` it never puts the final `None` into the queue.

https://github.com/broadinstitute/tensorqtl/blob/17bbb84b59a8db91deca333e356ab3f495c3824b/tensorqtl/genotypeio.py#L49-L52

Thus the main thread is left waiting forever on this line for the next value.

https://github.com/broadinstitute/tensorqtl/blob/17bbb84b59a8db91deca333e356ab3f495c3824b/tensorqtl/genotypeio.py#L55

The net result is that the background thread prints an exception to the console, but the program keeps running forever.

How to reproduce
---

* `single_uniform_expression.genotype.bed`:
    ```
    #chr	start	end	pid	A	B	C
    chr1	1999999	2000000	chr1:2000000:A:C	0	1	2
    ```

* `single_uniform_expression.phenotype.bed`:
    ```
    #chr	start	end	pid	A	B	C
    chr1	2000000	2000001	EXMPL	0	0	0
    ```

* Command line:
    ```Shell
    tensorqtl \
    single_uniform_expression.genotype.bed \
    single_uniform_expression.phenotype.bed \
    single_uniform_expression \
    --mode cis_nominal \
    --seed 777
    ```

Output
---

```Python
Warning: 'rfunc' cannot be imported. R with the 'qvalue' library, and the 'rpy2' Python package are needed.
[Jun 18 11:36:13] Running TensorQTL: cis-QTL mapping
  * WARNING: using CPU!
  * using seed 777
  * reading phenotypes (single_uniform_expression.phenotype.bed)
  * cis-window detected as position ± 1,000,000
  * loading genotypes
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 3 samples
  * 1 phenotypes
  * 1 variants
  * cis-window: ±1,000,000
    ** dropping 1 constant phenotypes
  * Computing associations
    Mapping chromosome chr1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/kshakir/miniconda3/envs/tensorqtl/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/kshakir/miniconda3/envs/tensorqtl/lib/python3.9/site-packages/tensorqtl/genotypeio.py", line 50, in run
    for item in self.generator:
  File "/Users/kshakir/miniconda3/envs/tensorqtl/lib/python3.9/site-packages/tensorqtl/genotypeio.py", line 489, in generate_data
    chr_offset = offset_dict[chrom]
KeyError: 'chr1'
```

"Exception in thread Thread-1" is printed above, and the program does not terminate.

Notes
---

We discovered this when a new user wanted to test a single gene using our pipeline. We normalize the gene expression data, so the number of transcripts of each sample for that single gene was the same value: `1000000`. The pipeline then ran tensorQTL on Google Compute Engine renting GPUs, and we only realized after the weekend that we had spent a lot of money on stuck jobs when we got budget alerts from Google. 💸

**Comment by francois-a** [comment]
Thanks for this and the PR! e97f4ea903b47b139a47de6e9d2e3bf140e49d6f adds error handling for cases like this.
