### ISSUE TITLE
invalid value encountered in sqrt error in cis-QTL mapping

### ISSUE THREAD

**Issue by Ruby-1869** [broadinstitute/tensorqtl#14]
Hi,

I've done the cis-QTL mapping with cis.map_nominal function and got the results, but when I tried to run  `cis_df = cis.map_cis(genotype_df, variant_df, phenotype_df, phenotype_pos_df, covariates_df, nperm=100, seed = 1234)` it kept giving me the same error below even when I used the example GEUVADIS.445 data. 

>     processing phenotype 19795/19798
>     processing phenotype 19796/19798
>     processing phenotype 19797/19798
>     processing phenotype 19798/19798
> 
>     /home/il/faststorage/miniconda3/envs/tensorQTL_new/lib/python3.6/site-packages/tensorqtl/core.py:217: RuntimeWarning: invalid value encountered in sqrt
>     return 2*stats.t.cdf(-np.abs(np.sqrt(tstat2)), dof)
>     /home/il/faststorage/miniconda3/envs/tensorQTL_new/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
>      return (a < x) & (x < b)
>     /home/il/faststorage/miniconda3/envs/tensorQTL_new/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
>     return (a < x) & (x < b)
>     /home/il/faststorage/miniconda3/envs/tensorQTL_new/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1827: RuntimeWarning: invalid value encountered in greater_equal
>     cond2 = (x >= np.asarray(_b)) & cond0

I'm not sure which problem caused this error?

Many thanks.

**Comment by Ruby-1869** [comment]
Anyone can help?

**Comment by francois-a** [comment]
Hi,
Can you please provide a more specific, reproducible example? I don't see this error when running the [example notebook](https://github.com/broadinstitute/tensorqtl/blob/master/example/tensorqtl_examples.ipynb).

**Comment by Ruby-1869** [comment]
Dear François,

Attached are the scripts I used and the error message. I worked on the
university cluster and have to install the tensorQTL in an anaconda
environment. I used the GEUVADIS.445 data directly downloaded from the
github page. The command I used to run the task was:

sbatch run_tensorQTL_cis_empirical.sh

The script simply activated the anaconda environment and submit the work to
the cluster, and then tensorQTL_cis_empirical.py did the work. (I basically
directly copy-paste the python code from the example notebook)

The error message is in run_tensorQTL_cis_empirical.sh-11918986.out

My final goal is to run the interactive QTL mapping. I've successfully
finished the nominal QTL mapping (with and without interaction), but when I
tried to run the empirical mapping, it always gave me the same error.

Many thanks for your help.


Best,
Ruby Lo

**Comment by francois-a** [comment]
Can you please post the scripts in the issue here on GitHub? email attachments don't work for these.

**Comment by Ruby-1869** [comment]
Sorry. 
This is the run_tensorQTL_cis_empirical.sh script.

```
#!/bin/bash


#SBATCH -c 4
#SBATCH --gres=gpu:1              # Number of GPUs (per node)
#SBATCH -p gpu
#SBATCH --mem=50G               # memory (per node)
#SBATCH --time=48:00:00


#activate conda environment which installed the tensorQTL
source activate tensorQTL_new

WKDIR=${SLURM_SUBMIT_DIR}/GEUVADIS.445  

python ${SLURM_SUBMIT_DIR}/tensorQTL_cis_empirical.py ${WKDIR} 

```

And this is the tensorQTL_cis_empirical.py script.

```
#!/usr/bin/env python


import os, glob, sys
import pandas as pd
from logging import debug, warning, error, getLogger
from optparse import OptionParser
import numpy as np
import tensorqtl
from tensorqtl import genotypeio, cis, trans
import matplotlib.pyplot as plt

#Variables
wk_dir=sys.argv[1]


# path to data
plink_prefix_path = '%s/GEUVADIS.445_samples.GRCh38.20170504.maf01.filtered' % (wk_dir)
expression_bed = '%s/GEUVADIS.445_samples.expression.bed.gz' % (wk_dir)
covariates_file = '%s/GEUVADIS.445_samples.covariates.txt' % (wk_dir)
prefix =  '%s/GEUVADIS.445_samples' % (wk_dir)



# load phenotypes and covariates
phenotype_df, phenotype_pos_df = tensorqtl.read_phenotype_bed(expression_bed)
covariates_df = pd.read_csv(covariates_file, sep='\t', index_col=0).T


# PLINK reader for genotypes
pr = genotypeio.PlinkReader(plink_prefix_path)
genotype_df = pr.load_genotypes()
variant_df = pr.bim.set_index('snp')[['chrom', 'pos']]


# cis_empirical
cis_df = cis.map_cis(genotype_df, variant_df, phenotype_df, phenotype_pos_df, covariates_df, nperm=100, seed = 1234)
```


Thanks.

**Comment by francois-a** [comment]
This script runs fine on my end. I suspect it might be the input files -- can you please download the files from the [example notebook](https://github.com/broadinstitute/tensorqtl/blob/master/example/tensorqtl_examples.ipynb) again? The PLINK files should end with `.filtered.nodup.*`. And please make sure to run the latest version of tensorQTL.

Here's the output you should see:
```
cis-QTL mapping: empirical p-values for phenotypes
  * 445 samples
  * 19836 phenotypes
  * 26 covariates
  * 13369268 variants
  * using seed 1234
  * checking phenotypes: 19836/19836
    ** dropping 38 phenotypes without variants in cis-window
  * computing permutations
    processing phenotype 19798/19798
  Time elapsed: 5.33 min
done.

```
