### ISSUE TITLE
cis_independent requires covariate_df

### ISSUE THREAD

**Issue by MarcElosua** [broadinstitute/tensorqtl#142]
Hi tensorQTL team,

Thank you so much for developing and maintaining such an amazing tool! 

I'm running tensorQTL to identify in `cis_independent` mode like this:
```
python3 -m tensorqtl $plink_prefix_path $filepath $out \
    --cis_output $cis \
    --mode cis_independent
```

I previously regressed out the covariate effects from `$filepath` as they do [here](https://github.com/immunogenomics/sceQTL/blob/main/scripts/pseudobulk/02_normalize.R) and, therefore, I don't need to pass the `--covariates` flag.

When I run tensorQTL in `cis_independent` mode I get the following error:
```
.....lib/python3.9/site-packages/tensorqtl/cis.py", line 793, in map_independent
    assert covariates_df.index.equals(phenotype_df.columns)
AttributeError: 'NoneType' object has no attribute 'index'
```

I went to check the requirements of [map_independent](https://github.com/broadinstitute/tensorqtl/blob/17bbb84b59a8db91deca333e356ab3f495c3824b/tensorqtl/cis.py#L784) and it appears `covariates_df` is a mandatory. argument when it is not for [map_cis](https://github.com/broadinstitute/tensorqtl/blob/17bbb84b59a8db91deca333e356ab3f495c3824b/tensorqtl/cis.py#L628).

Is it necessary to have the covariates file for this? and if it is, would you have any workarounds I could use to not pass covariates since my gene expression data has already regressed them out?

Thank you very much!
Marc

**Comment by francois-a** [comment]
Thanks for reporting this! As of 3471680f96fea08a5e98bd277b98fe024e2aef9e `covariates_df` is optional for `map_independent`.
