### ISSUE TITLE
Phenotype file format

### ISSUE THREAD

**Issue by malonzm1** [broadinstitute/tensorqtl#143]
Hi,

In the example file for the phenotype there are negative expression values. May I know what transformation was used from sequencing read counts?

**Comment by francois-a** [comment]
Please see the Methods section in the supplement of https://www.science.org/doi/10.1126/science.aaz1776

**Comment by malonzm1** [comment]
Thanks. Just to check, TPMs were inverse normal transformed across samples?

**Comment by francois-a** [comment]
Counts were first normalized using the TMM method, and then inverse normal transformed. Please see [here](https://github.com/broadinstitute/gtex-pipeline/blob/6983de2e5e6c7fdfe689bc797e8d6b62468bc1d1/qtl/src/eqtl_prepare_expression.py) for additional details on the normalization procedure.

**Comment by malonzm1** [comment]
Thanks. Just checking, for the TMM transformation step, the counts are not log transformed?

**Comment by francois-a** [comment]
That's right. The preprocessing pipeline for GTEx is available [here](https://github.com/broadinstitute/gtex-pipeline/blob/master/qtl/src/eqtl_prepare_expression.py).

**Comment by malonzm1** [comment]
Thanks. And the filtering of genes is performed after TMM and before inverse normal transformation?
