### ISSUE TITLE
permutations IndexError

### ISSUE THREAD

**Issue by gn5** [broadinstitute/tensorqtl#15]
Hi,

At the permutations step, tensorqtl gives the error:
```
  File "/lustre/scratch118/humgen/resources/conda_envs/tensorqtl/lib/python3.5/site-packages/tensorqtl/cis.py", l$
    return r_nominal_t[ix], std_ratio_t[ix], ix, r2_perm_t, genotypes_t[ix]                                       
IndexError: too many indices for tensor of dimension 0
```
see full log:
[log.txt](https://github.com/broadinstitute/tensorqtl/files/4661602/log.txt)

The command executed was
`python3 -m tensorqtl plink_franke.filtered expression_data.filtered.bed.gz franke_out     --covariates franke_covariates.txt     --mode cis` 
Using tensorqtl version 1.0.2 installed via pip.
I've unsuccessfully tried a couple of number of permutations and seed.

The input data is about 170MB, which I can provide if you would like to reproduce the issue.

Any idea what might have caused the error?
Thanks!

Guillaume

**Comment by gn5** [comment]
I should also mention that the same code/environment runs successfully on the GEUVADIS.445 test data.

**Comment by francois-a** [comment]
Hi,
This issue should be fixed in v1.0.3. If not, please do share the data to reproduce the error.

**Comment by gn5** [comment]
Yes updating to v1.0.3 via the repo solved the issue. Thanks.

**Comment by francois-a** [comment]
Sorry, I had forgotten to push this to PyPI. Done now, thanks.
