### ISSUE TITLE
variant ids missing [dots only]

### ISSUE THREAD

**Issue by liaguiro** [broadinstitute/tensorqtl#150]
Hello,

I got the top association for each phenotype  after running the cis-mapping:interaction. I'm getting dots in the variant id column, so I don't know which SNP id is significantly associated to the phenotype id. 
Is this an error? or can you please recommend a way to retrieve the SNP ids?

Here are the log files:
[Aug 30 14:17:16] Running TensorQTL: cis-QTL mapping
  * WARNING: using CPU!
  * reading phenotypes (TPMmatrix.tensorqtl_format.bed)
  * cis-window detected as position ± 500,000
  * reading covariates (covariate.matrix.txt)
  * reading interaction term(s) (interaction.tensorqtl.txt)
  * loading genotypes
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 288 samples
  * 22493 phenotypes
  * 1 covariates
  * 1111 variants
  * including 1 interaction term(s)
    * using 0.05 MAF threshold
  * cis-window: ±500,000
  * Computing associations
    Mapping chromosome NC_035161.2
    time elapsed: 0.34 min
    Mapping chromosome NC_035162.2
    time elapsed: 0.39 min
    Mapping chromosome NC_035163.2
    time elapsed: 0.43 min
    Mapping chromosome NC_035164.2
    time elapsed: 0.47 min
    Mapping chromosome NC_035165.2
    time elapsed: 0.51 min
    Mapping chromosome NC_035166.2
    time elapsed: 0.55 min
    Mapping chromosome NC_035167.2
    time elapsed: 0.57 min
    Mapping chromosome NC_035168.2
    time elapsed: 0.61 min
    Mapping chromosome NC_035169.2
    time elapsed: 0.66 min
    Mapping chromosome NC_035170.2
    time elapsed: 0.69 min
    Mapping chromosome NC_035171.2
    time elapsed: 0.72 min
    Mapping chromosome NC_035172.2
    time elapsed: 0.74 min
    Mapping chromosome NC_035173.2
    time elapsed: 0.77 min
    Mapping chromosome NC_035174.2
    time elapsed: 0.81 min
    Mapping chromosome NC_035175.2
    time elapsed: 0.86 min
    Mapping chromosome NC_035176.2
    Mapping chromosome NC_035176.2
    time elapsed: 0.89 min
    Mapping chromosome NC_035177.2
    time elapsed: 0.92 min
    Mapping chromosome NC_035178.2
    time elapsed: 0.95 min
done.
[Aug 30 14:18:21] Finished mapping
Error in library(vimcom) : there is no package called ‘vimcom’
[Aug 30 14:17:16] Running TensorQTL: cis-QTL mapping
  * WARNING: using CPU!
  * reading phenotypes (TPMmatrix.tensorqtl_format.bed)
  * cis-window detected as position ± 500,000
  * reading covariates (covariate.matrix.txt)
  * reading interaction term(s) (interaction.tensorqtl.txt)
  * loading genotypes
^MMapping files:   0%|          | 0/3 [00:00<?, ?it/s]^MMapping files: 100%|██████████| 3/3 [00:00<00:00, 37.96it/s]
/.conda/envs/tensorqtl/lib/python3.11/site-packages/tensorqtl/cis.py:189: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  interaction_mask_t = torch.BoolTensor(mask_s).to(device)
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 288 samples
  * 22493 phenotypes
  * 1 covariates
  * 1111 variants
  * including 1 interaction term(s)
    * using 0.05 MAF threshold
  * cis-window: ±500,000
    ** dropping 138 phenotypes on chrs. without genotypes
^M  * checking phenotypes: 1000/22355^M  * checking phenotypes: 2000/22355^M  * checking phenotypes: 3000/22355^M  * checking phenotypes: 4000/22355^M  * checking phenotypes: 5000/22355^M  * checking phenotypes: 6000/22355^M  * checking .... [intentionally cut output here]
    ** dropping 5251 phenotypes without variants in cis-window
  * Computing associations
    Mapping chromosome NC_035161.2
^M    processing phenotype 1/17104^M    processing phenotype 2/17104^M    processing phenotype 3/17104^M    processing phenotype 4/17104^M    processing phenotype 5/17104^M    processing phenotype 6/17104^M    processing phenotype 7/171
04^M    processing phenotype 8/17104^M    processing phenotype 9/17104^M    processing phenotype 10/17104^M    processing phenotype 11/17104^M    processing phenotype 12/17104^M    processing phenotype 13/17104^M    processing phenotype
 14/17104^M    processing phenotype 15/17104^M    processing phenotype 16/17104^M    processing phenotype 17/17104^M    processing phenotype 18/17104^M    processing phenotype 19/17104^M    processing phenotype 20/17104^M    processing
.... [intentionally cut output here]
/.conda/envs/tensorqtl/lib/python3.11/site-packages/tensorqtl/cis.py:539: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.01415352 0.15107468 0.00317133 ... 0.62216019 0.73657944 0.67813685]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  best_assoc.loc[m, 'pval_g'] =  2*stats.t.cdf(-best_assoc.loc[m, 'pval_g'].abs(), idof)
/.conda/envs/tensorqtl/lib/python3.11/site-packages/tensorqtl/cis.py:541: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[6.44476976e-01 2.937
33919e-01 7.05662460e-01 ... 6.46820693e-01
 7.17379209e-07 1.01459954e-02]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  best_assoc.loc[m, 'pval_i'] =  2*stats.t.cdf(-best_assoc.loc[m, 'pval_i'].abs(), idof)
/.conda/envs/tensorqtl/lib/python3.11/site-packages/tensorqtl/cis.py:542: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.31639619 0.57707129 0.42047863 ... 0.0411925  0.92769589 0.60062434]' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  best_assoc.loc[m, 'pval_gi'] = 2*stats.t.cdf(-best_assoc.loc[m, 'pval_gi'].abs(), idof)
    time elapsed: 0.95 min
done.
[Aug 30 14:18:21] Finished mapping

**Comment by francois-a** [comment]
That's an issue with the input genotypes, and you'll need to fix this in the VCF/plink files before running tensorQTL.
