### ISSUE TITLE
paramter best_only

### ISSUE THREAD

**Issue by xtmgah** [broadinstitute/tensorqtl#16]
Hello:

Can you let me know if '--best-only' working in cis or trans mode? did this paramter work after '--pval_threshold'? Thanks.

**Comment by francois-a** [comment]
Hi,
This option enables writing only the lead association for each phenotype when mapping with an interaction term (in cis mode). This wasn't working properly in the CLI, but is fixed in 2b212dea3cbaec25e6f71ebc2a55dca4ccf8f9dd.
