### ISSUE TITLE
bed file when having multiple TSS

### ISSUE THREAD

**Issue by liaguiro** [broadinstitute/tensorqtl#170]
Hello,

I got the TSSs from the gtf file, and some genes have multiple TSSs (this happens for genes with a "trans-splicing" label). My gene expression matrix only has one row (entry) per gene.  What do you recommend to do when constructing the bed expression file? duplicate the gene expression row (entry) in the matrix, one for each TSS?

Thanks!

**Comment by francois-a** [comment]
Hi, I recommend collapsing the annotation — please see https://github.com/broadinstitute/gtex-pipeline/tree/master/gene_model.
