### ISSUE TITLE
Setting a seed

### ISSUE THREAD

**Issue by GlastonburyC** [broadinstitute/tensorqtl#2]
Is there any ability to set a seed for the tensorflow ops, given it's a non-deterministic optimisation process?

**Comment by francois-a** [comment]
Yes, you can provide this with the `--seed` option (the only non-deterministic component is the permutations, and these are pre-computed in numpy).

**Comment by GlastonburyC** [comment]
Hey @francois-a thanks! :) - That's the CLI argument, how about the python function itself is it just `seed=`?

**Comment by francois-a** [comment]
Yes, exactly -- all functions that perform permutations have this option.
