### ISSUE TITLE
ValueError: Names should be an ordered collection.

### ISSUE THREAD

**Issue by aarbduarte** [broadinstitute/tensorqtl#21]
Thank you for the hard work.

I've been using tensorqtl for the past 3-4 months and recently it started erroring when reading the genotype file, even with the demonstration files:

>>> pr = genotypeio.PlinkReader(plink_prefix_path)
Mapping files:   0%|                                                                                                                                                                    | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aduarte/tensorqtl/tensorqtl/genotypeio.py", line 135, in __init__
    self.bim, self.fam, self.bed = read_plink(plink_prefix_path, verbose=verbose)
  File "/home/aduarte/tensorqtl/example/venv/lib/python3.6/site-packages/pandas_plink/_read.py", line 115, in read_plink
    bim = _read_file(fn, lambda fn: _read_bim(fn["bim"]), pbar)
  File "/home/aduarte/tensorqtl/example/venv/lib/python3.6/site-packages/pandas_plink/_read.py", line 326, in _read_file
    data.append(read_func(f))
  File "/home/aduarte/tensorqtl/example/venv/lib/python3.6/site-packages/pandas_plink/_read.py", line 115, in <lambda>
    bim = _read_file(fn, lambda fn: _read_bim(fn["bim"]), pbar)
  File "/home/aduarte/tensorqtl/example/venv/lib/python3.6/site-packages/pandas_plink/_read.py", line 358, in _read_bim
    df = _read_csv(fn, header)
  File "/home/aduarte/tensorqtl/example/venv/lib/python3.6/site-packages/pandas_plink/_read.py", line 341, in _read_csv
    engine="c",
  File "/home/aduarte/tensorqtl/example/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/aduarte/tensorqtl/example/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 449, in _read
    _validate_names(kwds.get("names", None))
  File "/home/aduarte/tensorqtl/example/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 417, in _validate_names
    raise ValueError("Names should be an ordered collection.")
ValueError: Names should be an ordered collection.

I believe it is due to the most recent pandas update.
Thank you for your time

**Comment by francois-a** [comment]
Hi, thanks for reporting this! This error is indeed due to the most recent pandas version, and occurs in `pandas_plink`. I posted an issue (https://github.com/limix/pandas-plink/issues/18). In the meantime, please use Pandas 1.0.5.

**Comment by aarbduarte** [comment]
I downgraded pandas to 1.0.5 by editing the requirements.
Furthermore when performing cis nominal mapping I retrieve another error:

`cis = cis.map_nominal(genotype_df, variant_df, phenotype_df, phenotype_pos_df, covariates_df, prefix)
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 445 samples
  * 19836 phenotypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aduarte/tensorqtl/tensorqtl/cis.py", line 157, in map_nominal
    assert np.all(phenotype_df.columns==covariates_df.index)
AssertionError`

I'm using the provided example dataset as assurance of input quality

**Comment by francois-a** [comment]
This is fixed in d812a2a7b5fe7e6b62f088343cfdb23ed24e94b4. The argument order of `map_nominal` was changed to make covariates optional.

**Comment by aarbduarte** [comment]
Thank you for the quick comeback, it fixed that problem.

Now I can go all the way to nominal mapping where it chrashes hard:

`
>>> import pandas as pd
>>> import tensorqtl
>>> from tensorqtl import genotypeio, cis, trans
>>> print('PyTorch {}'.format(torch.__version__))
PyTorch 1.6.0
>>> print('Pandas {}'.format(pd.__version__))
Pandas 1.0.5
>>> plink_prefix_path = './example/GEUVADIS.445_samples.GRCh38.20170504.maf01.filtered.nodup.bed'
>>> expression_bed = './example/GEUVADIS.445_samples.expression.bed.gz'
>>> covariates_file = './example/GEUVADIS.445_samples.covariates.txt'
>>> prefix = 'Geuvadis_results.'
>>> phenotype_df, phenotype_pos_df = tensorqtl.read_phenotype_bed(expression_bed)
\t', index_col=0).T
>>> covariates_df = pd.read_csv(covariates_file, sep='\t', index_col=0).T
>>> pr = genotypeio.PlinkReader(plink_prefix_path)
Mapping files: 100%|████████████████████████| 3/3 [00:23<00:00,  7.67s/it]
>>> genotype_df = pr.load_genotypes()
>>> variant_df = pr.bim.set_index('snp')[['chrom', 'pos']]

>>> cis.map_nominal(genotype_df, variant_df,
...                 phenotype_df.loc[phenotype_pos_df['chr']=='chr18'],
...                 phenotype_pos_df.loc[phenotype_pos_df['chr']=='chr18'],
...                 prefix, covariates_df=covariates_df)
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 445 samples
  * 301 phenotypes
  * 26 covariates
  * 13369268 variants
  * checking phenotypes: 301/301
  * Computing associations
    Mapping chromosome chr18
    processing phenotype 301/301
    time elapsed: 0.83 min
    * writing output
done.
>>> cis_df = cis.map_cis(genotype_df, variant_df,
...                      phenotype_df.loc[phenotype_pos_df['chr']=='chr18'],
...                      phenotype_pos_df.loc[phenotype_pos_df['chr']=='chr18'],
...                      covariates_df=covariates_df, seed=123456)
cis-QTL mapping: empirical p-values for phenotypes
  * 445 samples
  * 301 phenotypes
  * 26 covariates
  * 13369268 variants
  * using seed 123456
  * checking phenotypes: 301/301
  * computing permutations
    processing phenotype 8/301R[write to console]:
 *** caught illegal operation ***

R[write to console]: address 0x7fe9da6ea409, cause 'illegal operand'

R[write to console]:
Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

Selection:`

**Comment by francois-a** [comment]
The entire notebook runs without problems for me, with the same module versions. What environment are you running this in, and why are you getting R errors at the end?

**Comment by aarbduarte** [comment]
I'm using RStudio's terminal on a linux machine to run all commands
```
uname -a
Linux rey 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by francois-a** [comment]
Can you try to run this within python/ipython/jupyter instead?

**Comment by ramiromagno** [comment]
@francois-a: Aren't the R errors resulting from R code being using through rpy2?

**Comment by francois-a** [comment]
No, R is only used at the very end, to calculate q-values. The code above crashes on batch 8, which suggests that the error originates with the first batch processed on the GPU (batches are pre-loaded in a separate thread). Without seeing the python stack trace it's impossible to guess what is causing this.

**Comment by francois-a** [comment]
The original error is fixed in https://github.com/limix/pandas-plink/pull/19. @aarbduarte please open a new issue if you still can't get the example notebook to run.
