### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by stivenming** [broadinstitute/tensorqtl#22]
I have downloaded your example data GEUVADIS and used this command 
```
python -m tensorqtl .\GEUVADIS.445_samples.GRCh38.20170504.maf01.filtered.nodup .\GEUVADIS.445_samples.expression.bed.gz GEUVADIS.445_samples --covariates .\GEUVADIS.445_samples.covariates.txt --mode cis
```
got this error
![image](https://user-images.githubusercontent.com/45038348/90952146-dc906f00-e493-11ea-83cf-0c209d3aaea3.png)
Can you give me some advices ? thanks much

**Comment by stivenming** [comment]
I found that the cause of the error is `tensor.dtype` of  `genotype_ix_t` . `torch.from_numpy()` will define `tensor.dtype` as `torch.int32`. I solved this error by adding `genotype_ix_t = genotype_ix_t.type(torch.LongTensor).to(device)` and then working.

**Comment by francois-a** [comment]
Please update to [v1.0.4](https://github.com/broadinstitute/tensorqtl/releases/tag/v1.0.4) (changes elsewhere should fix this, but had not yet been pushed to a new release).
