### ISSUE TITLE
cis mode gives wrong top SNP when monomorphic SNP is present

### ISSUE THREAD

**Issue by daniel-munro** [broadinstitute/tensorqtl#26]
Hello, when running cis mode I'm getting two different top SNPs for a gene depending on whether a third SNP, which is monomorphic, is present. In that case it seems that `pval_nominal`, `ma_samples`, `ma_count`, etc. are correct, but not the `variant_id`, `tss_distance`, etc. For example (files: [test.zip](https://github.com/broadinstitute/tensorqtl/files/5413560/test.zip)):

```
python -m tensorqtl --mode cis geno1 expr.bed.gz out1 --covariates covar.txt
```

That outputs:

```
phenotype_id    num_var beta_shape1     beta_shape2     true_df pval_true_df    variant_id      tss_distance    ma_samples      ma_count        maf     ref_factor      pval_nominal
    slope   slope_se        pval_perm       pval_beta
ENSRNOG00000014290      30      0.963347        3.1823  68.246  0.0478687       chr1:4435151    -730709 53      65      0.411392        1       0.0482753       -0.0647425      0.0321917       0.160684        0.156524
```

When chr1:4403830, which is all homozygous alt, is excluded, the SNP following chr1:4435151 becomes the top one:

```
python -m tensorqtl --mode cis geno2 expr.bed.gz out2 --covariates covar.txt
```

That outputs:

```
phenotype_id    num_var beta_shape1     beta_shape2     true_df pval_true_df    variant_id      tss_distance    ma_samples      ma_count        maf     ref_factor      pval_nominal
    slope   slope_se        pval_perm       pval_beta
ENSRNOG00000014290      29      0.944845        3.14276 68.2232 0.0479062       chr1:4435247    -730613 53      65      0.411392        1       0.0482753       -0.0647425      0.0321917       0.158984        0.161257
```

`cis_nominal` mode produces the correct values for these two SNPs in both cases, with `ma_samples` and `ma_count` matching what I see in the original VCF:

```
phenotype_id    variant_id  tss_distance       maf  ma_samples  ma_count  pval_nominal     slope  slope_se
...
ENSRNOG00000014290  chr1:4435151       -730709  0.082278          13        13      0.387017 -0.049743  0.057135
ENSRNOG00000014290  chr1:4435247       -730613  0.411392          53        65      0.048275 -0.064742  0.032192
```

I'm using the latest version from GitHub.

**Comment by francois-a** [comment]
Hi Dan,

Many thanks for reporting this and for providing an example! This bug occurred because I wasn't updating the variant index after filtering out monomorphic SNPs. Please check out the latest commit (dfa1deb45934e7b814d80d7868d5d24cf64a53ca), which fixes this. I'll push it to a new release soon. 

In general, I recommend filtering out problematic SNPs beforehand (SNPs not in HWE etc).

**Comment by daniel-munro** [comment]
Thanks for the quick fix! Yeah, I should filter those SNPs out beforehand to be safe.
