### ISSUE TITLE
[QST] Binary phenotypes

### ISSUE THREAD

**Issue by mikacashman** [broadinstitute/tensorqtl#27]
I have a question - Does tensorQTL support binary phenotypes or just quantitative?  It looks like FastQTL only allows float phenotype values thus my question.

**Comment by francois-a** [comment]
Hi, at the moment only quantitative phenotypes are supported.

**Comment by mikacashman** [comment]
Thanks for the response.  We were seeing great performance using tensorQTL but some of our work requires binary phenotypes.  Would love to see it supported in the future.
