### ISSUE TITLE
Running tensorqtl with interaction term on command line

### ISSUE THREAD

**Issue by nbbarrientos** [broadinstitute/tensorqtl#28]
Hello,

First off, congratulations and thank you for this great tool. I have a few questions regarding the usage of tensorqtl when an interaction term is present. If running in command line, I'm assuming the interaction term would be a file. What format should this file follow? I'm having trouble understanding how to create this file. 

Once I know the file format and I have all the files ready, would the appropriate way to run tensorqtl on command line be as follow:

python3 -m tensorqtl ${plink_prefix_path} ${expression_bed} ${prefix} \
    --covariates ${covariates_file} \
    --interaction ${interaction_term} \
    --mode cis_nominal

Additionally, if I wanted to run this analysis in permutation mode, sort of like FastQTL, how would I go about it?

Thank you for your help. 

Nelson Barrientos

**Comment by francois-a** [comment]
Hi, thanks! The format of the interactions file should be tab-delimited, two columns, with sample ID in the first column and value of the interaction term in the second (a single line header can be present but is optional).

That's the correct command line. For interactions permutations are not supported, instead, the effective number of independent variants is computed using eigenMT (please see [here](https://github.com/broadinstitute/tensorqtl#cis-qtl-mapping-interactions)).

**Comment by nbbarrientos** [comment]
Thank you for your response. I have a clearer picture now of how to format the interaction file. 

Thanks

**Comment by nbbarrientos** [comment]
Hello again,

I ran tensorqtl with the above command line and bumped into the following error:

Traceback (most recent call last):
  File "/apps/software/standard/core/intel/20.0/intelpython3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/apps/software/standard/core/intel/20.0/intelpython3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nbb5vf/.local/lib/python3.7/site-packages/tensorqtl/__main__.py", line 2, in <module>
    tensorqtl.main()
  File "/home/nbb5vf/.local/lib/python3.7/site-packages/tensorqtl/tensorqtl.py", line 120, in main
    write_top=True, write_stats=not args.best_only, logger=logger, verbose=True)
  File "/home/nbb5vf/.local/lib/python3.7/site-packages/tensorqtl/cis.py", line 219, in map_nominal
    chr_res['b_gi'] =    np.empty(n, dtype=np.float32)
MemoryError: Unable to allocate array with shape (104430772,) and data type float32

I was wondering if I could get some help. Thanks.

Nelson

**Comment by francois-a** [comment]
This is a memory error when allocating the output arrays, so the easiest solution is to increase memory. However, the size of this array seems too large. What does your data look like? How many variants, phenotypes, etc?

**Comment by nbbarrientos** [comment]
Thank you for your quick response. This is the summary of my data:

[Nov 16 14:45:27] Running TensorQTL: cis-QTL mapping
  * WARNING: using CPU!
  * reading phenotypes (./CORONARY5.leafcutter.bed.gz)
  * reading covariates (./CORONARY5.combined_covariates.txt)
  * reading interaction term (./interaction.txt)
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 149 samples
  * 155988 phenotypes
  * 8 covariates
  * 10060927 variants
  * including interaction term
    * using 0.05 MAF threshold

**Comment by francois-a** [comment]
The large number of phenotypes explains the memory error. Are you running them individually on purpose? Otherwise, for splicing phenotypes I recommend using grouped mode (by providing `phenotype_groups`); this way for each group/gene, only the top phenotype-variant pair is returned.

**Comment by nbbarrientos** [comment]
If I provide phenotype groups, do both the phenotype id and group id have to be in the expression_bed file? Sort of like how they are required for QTLtools?

**Comment by francois-a** [comment]
For tensorQTL the phenotype BED file doesn't need any changes, and only one identifier should be present. A separate tab-delimited file, mapping phenotype IDs to group (gene) IDs should be provided with `phenotype_groups`.

**Comment by nbbarrientos** [comment]
Thank you very much!
