### ISSUE TITLE
The function of "filter_cis" doesn't work in trans-eQTL analysis 

### ISSUE THREAD

**Issue by xwBio** [broadinstitute/tensorqtl#3]
I am performing a trans-eQTL analysis using tensorQTL tools. But I found that SNPs within +/- 5M of the target gene were not filtered. Could you please fix the problem?

**Comment by xwBio** [comment]
Hi, many thanks for your reply.
Please find the below code I used for analysis:
python -m tensorqtl ${plink_prefix_path} ${wd}/${prefix}_rpkm.qnorm.std.bed.gz ${prefix} \
    --covariates ${wd}/${prefix}_combine_covariates.txt \
    --mode trans \
    --output_text \
    --return_r2 \
    -o  ${wd}

**Comment by francois-a** [comment]
Ok, so this should definitely work. What format are the variant IDs in your VCF in? `filter_cis` currently assumes that variants are in the format `chr_pos_alt_ref_build`, and extracts the variant position from these IDs.

**Comment by xwBio** [comment]
> Ok, so this should definitely work. What format are the variant IDs in your VCF in? `filter_cis` currently assumes that variants are in the format `chr_pos_ref_alt_build`, and extracts the variant position from these IDs.

Thank you very much.
The SNP name in my genotype file was the rs number. That may be the reason for the issue. 
If the tensorQTL could be applied to variants with the rs number for trans-QTL analysis, it would be much better.
Thanks for your great work again.

**Comment by francois-a** [comment]
This is fixed in the latest version. Thanks for catching this issue!
