### ISSUE TITLE
adding random effects for shared donors

### ISSUE THREAD

**Issue by jackhump** [broadinstitute/tensorqtl#31]
Dear Francois,

I have a dataset with multiple similar tissues from more or less the same set of donors (very much analogous to GTEx).  

What I'm hoping to do is to increase my QTL discovery power for subsequent colocalisation with disease GWAS, which requires meta-analysed beta and standard errors for each SNP-Gene pair. I ran METASOFT with an RE2 model on the tensorQTL summary stats but that doesn't account for donor sharing. MASHR is really nice but doesn't produce estimates per SNP, only per gene. The published software for performing these kinds of shared-donor meta-analyses are either horribly convoluted to run (Meta-Tissue), or focus on solely producing P-values rather than betas and standard errors (RECOV, RE2C).

Do you have any plans to be able to include random effects into the tensorQTL model so that one could account for shared donors in a single joint analysis? 
Alternatively, do you have any thoughts or tips on what the current state of the art is for this problem?

best wishes,

Jack

**Comment by Dongmeng-wang** [comment]
Hi Jack,

I also have this problem. I would like to include a sample id as a random effect in the model. Have you found any solutions to solve this problem? Thank you so much.

Diana

**Comment by francois-a** [comment]
A future version may support this, but this is currently not implemented.
