### ISSUE TITLE
unrecognized argument:--cis-_results 

### ISSUE THREAD

**Issue by Junjun-Xu** [broadinstitute/tensorqtl#33]
Hi
I want to use the mode of cis_independent for my own data ( wheat). But there are some fundamental problems. The mode of cis and cis_nominal can work properly. I don't know if there is a problem with my input.

code:python3 -m tensorqtl /data2/junxu/genotypeMaf005_87_bed/1.87.maf005 /data1/home/junxu/eQTL/zscore/parseBed/1.sorted.bed.gz /data2/junxu/1 --covariates /data1/home/junxu/eQTL/zscore/7_5_covariance.txt.gz --cis_results tensorResult/1.cis_qtl.txt.gz --mode cis_independent

error:__main__.py: error: unrecognized arguments: --cis_results tensorResult/1.cis_qtl.txt.gz
Thanks

**Comment by francois-a** [comment]
Hi,
The option should be `--cis_output`, not `--cis_results`. Thanks for pointing this out, I updated the README.

**Comment by Junjun-Xu** [comment]
thanks a lot.
