### ISSUE TITLE
interaction QTL

### ISSUE THREAD

**Issue by fastGEM** [broadinstitute/tensorqtl#34]
please provide detailed information about "interaction_s" in function below 

cis.map_nominal(genotype_df, variant_df, phenotype_df, phenotype_pos_df, covariates_df, prefix,
                interaction_s=interaction_s, maf_threshold_interaction=0.05,
                group_s=None, run_eigenmt=True, output_dir='.')

thanks.

**Comment by francois-a** [comment]
Hi, sorry for the late follow-up. I just updated the README. Please let me know if this is still unclear.

**Comment by maxozo** [comment]
I am also confused about the interaction_s=interaction_s. Would you be able to provide an example file? I am trying to provide a kinship interaction matrix - Sample Id x Sample Id

Thanks

**Comment by francois-a** [comment]
Hi, the interactions must be a pandas series with a single value per sample. It's currently not possible to fit a LMM, but I'm working on this.
