### ISSUE TITLE
Insignificant Interaction QTLs

### ISSUE THREAD

**Issue by shengxin321** [broadinstitute/tensorqtl#35]
Hi, 
   I know some cell types have no ieQTLs, but I am still want the nominal p value.
I found if there is no "*cis_qtl_top_assoc.txt.gz" output file, the "*.cis_qtl_pairs.chr*.parquet" file will be empty. Can this file be not empty?
Thank you.

**Comment by francois-a** [comment]
Hi, sorry for the late follow-up. Can you please try this again with v1.0.5? This fixes a bug resulting in empty outputs for some interaction inputs.
