### ISSUE TITLE
Unable to run cis.map_nomial with the example files

### ISSUE THREAD

**Issue by hzhu04** [broadinstitute/tensorqtl#36]
With the tensor_example Jupiter notebook, I find that I am not able to run the command [cis.map_nominal(genotype_df, variant_df, phenotype_df, phenotype_pos_df,
                covariates_df, prefix, output_dir='.')]. It reports an assertion error [assert np.all(phenotype_df.columns==covariates_df.index)] even after I changed the covariates_df to None.

**Comment by francois-a** [comment]
Please make sure to update to the latest version of tensorQTL and the notebook, it should run fine.

**Comment by anglixue** [comment]
Hi, I updated to the latest version but still got this error. 

I manually check the line and the condition is true

```
>>> assert np.all(phenotype_df.columns==covariates_df.index)
>>> np.all(phenotype_df.columns==covariates_df.index)
True
```

Is there anything else I could check why this happened?

**Comment by francois-a** [comment]
Are you still seeing this error with v1.0.7?

**Comment by anglixue** [comment]
It runs fine now with v1.0.7. Thank you!

**Comment by lintingyi2014** [comment]
I am seeing this error with v1.0.7.

**Comment by francois-a** [comment]
Please check with 1.0.9 instead.

**Comment by aa9gj** [comment]
Hi I am facing the same error with 1.0.9
