### ISSUE TITLE
A check on variant formatting and effect allele

### ISSUE THREAD

**Issue by biostair** [broadinstitute/tensorqtl#38]
Apologies if I've missed this explicitly somewhere else but I'd like to triple check:

- Where the variant id is formatted as chr_pos_a1_a2, is this always in the order/convention of chr_pos_ref_alt?

- Is the QTL effect allele the ALT allele? I.e. the slope values etc are reported relative to that allele.

**Comment by francois-a** [comment]
Hi, yes, both of these are correct. To clarify the second point, the effect is defined as the effect of the ALT allele relative to the REF allele.

**Comment by biostair** [comment]
Many thanks for the speedy clarification. And a handful more question to triple check something.

The MAF value is the Minor Allele Frequency. But this cannot be taken as the Effect Allele Frequency?

So if the REF is not the major allele in certain cases, then is that the reported MAF value, while the slope are still based on the ALT?

If that is true, then how can an Effect Allele Frequency be determined? Back to the input files to tensorQTL?

**Comment by francois-a** [comment]
Yes, these are all correct. The discrepancy of MAF and effect allele in cases where REF is the minor allele has come up a couple of times, and I think the most versatile solution is to report the ALT allele frequency instead of the MAF. I can make this change in the next release.

**Comment by biostair** [comment]
Thanks again!

So if I'm looking at results where someone else has generated the results using tensorQTL, I would need to have access to the input genotype/imputation files to be able to assess what the MAF value actually is? I.e. work out if the REF is the minor allele.

**Comment by francois-a** [comment]
Yes, unfortunately this will be the only way to be sure about the minor allele (but a reference panel might be sufficient for some cases, depending on sample size etc). I'm planning to make this change in the next couple of days if re-running tensorQTL is an option.

**Comment by biostair** [comment]
Unfortunately it's not my data to be able to run it again.
But many thanks for helping to clarify my questions and how to interpret the results from a run!
