### ISSUE TITLE
Interaction mode questions

### ISSUE THREAD

**Issue by iamjli** [broadinstitute/tensorqtl#39]
Hi there, 

Could you verify that my understanding of the interaction mode is correct? 

In my dataset, we have some disease and some control samples. Interaction mode can help identify QTLs that are condition-specific (via the `pval_i` and `pval_gi` columns)? 

Also, should condition still be provided as a covariate if I'm using it for the interaction parameter? 

Thank you!

**Comment by francois-a** [comment]
Hi,
Yes, that's correct -- variants with `pval_gi` that pass FDR correction are QTLs that depend on the tested condition. Condition should not be in the covariates, since that would introduce colinearity.

**Comment by iamjli** [comment]
thank you!
