### ISSUE TITLE
Interaction models with permutations

### ISSUE THREAD

**Issue by themagneticant** [broadinstitute/tensorqtl#41]
Hi!

Is there a possibility to run an interaction model with permutations? 

Thanks!

**Comment by francois-a** [comment]
It's generally not possible to use permutation tests for interaction models, see for example [this paper](https://doi.org/10.1111/j.1469-1809.2010.00572.x). This is why multiple-testing correction for interactions is performed with [eigenMT](https://www.cell.com/ajhg/fulltext/S0002-9297(15)00492-9).
