### ISSUE TITLE
interaction term

### ISSUE THREAD

**Issue by montenegrina** [broadinstitute/tensorqtl#42]
Hello,

To identify potential disease risk eQTLs, we planned to test for an interaction (eQTL x diabetes) term between genotype and diabetes status using the “modelLINEAR_CROSS” argument in MatrixEQTL. But we're wondering if the same type of analysis can be done with tensorQTL. Our goal is really to identify disease specific QTLs. Can you please advise if that is possible with your software and how?

Thanks
Ana

**Comment by francois-a** [comment]
Hi, yes, this is possible. Please take a look at the [section](https://github.com/broadinstitute/tensorqtl#cis-qtl-mapping-interactions) describing interactions in the readme.

**Comment by montenegrina** [comment]
Hello,

I am looking at that section:

cis.map_nominal(genotype_df, variant_df, phenotype_df, phenotype_pos_df, prefix,
                covariates_df=covariates_df,
                interaction_s=interaction_s, maf_threshold_interaction=0.05,
                run_eigenmt=True, output_dir='.', write_top=True,
write_stats=True)

Say I would have a covariate file that would have a column in it
indicating case/control status(diabetic versus non diabetic)

and I have to perform analysis for diabetes( disease specific) QTLs. I
would also control for sex and age. Can you please tell me how would I
put that info in the code above?

**Comment by francois-a** [comment]
The interaction covariate should be in `interaction_s`, other covariates (sex, age, etc.) in `covariates_df`.

The supplementary materials of this [paper](https://science.sciencemag.org/content/369/6509/eaaz8528/) describe how tensorQTL was used to map cell type interaction QTLs.

**Comment by montenegrina** [comment]
I want my interaction only to be with diabetes status (Pheno column) and I
want to control for sex and age.
Can you please let me know how the command above would look like?

**Comment by francois-a** [comment]
Please take a look at [tensorqtl_examples.ipynb](https://github.com/broadinstitute/tensorqtl/blob/master/example/tensorqtl_examples.ipynb). `covariates_df` would include sex and age in this case, and a pandas.Series would encode diabetes status.
