### ISSUE TITLE
independent eQTL process  Missing results

### ISSUE THREAD

**Issue by zpliu1126** [broadinstitute/tensorqtl#45]
Hi ~
I'm run `conditionally independent QTLs` model to find multiple independent signals of a eGene.

it ran successfully and got the result. But when I checked the number of eGene, I found that one eGene was missing from the output. Can I directly treat this missing eGene as having only one independent signal.  will this affect the final result?

And the following is the missing eGene item and  log file I used

```bash
[Apr 23 23:17:12] Running TensorQTL: cis-QTL mapping
  * WARNING: using CPU!
  * reading phenotypes (/data/cotton/zhenpingliu/LZP_RNAseq/03expres
  * reading covariates (/data/cotton/zhenpingliu/LZP_RNAseq/03expres
cis-QTL mapping: conditionally independent variants
  * 370 samples
  * 399/399 significant phenotypes
  * 23 covariates
  * 2658921 variants
  * computing independent QTLs
  Time elapsed: 13.59 min
done.
  * writing output
[Apr 23 23:31:42] Finished mapping
```
The information of  missing eGene 

| phenotype_id | num_var | beta_shape1 | beta_shape2 | true_df | pval_true_df | variant_id | tss_distance | ma_samples | ma_count | maf  | ref_factor | pval_nominal | slope | slope_se | pval_perm | pval_beta | qval | pval_nominal_threshold |
| ------------ | ------- | ----------- | ----------- | ------- | ------------ | ---------- | ------------ | ---------- | -------- | ---- | ---------- | ------------ | ----- | -------- | --------- | --------- | ---- | ---------------------- |
|Ghir_A12G018680|	3836|	1.00796|	86.6273|	311.949|	0.000156202|	SNP1417548|	809012|167|	195|	0.282609|	-1|	6.99197e-05|	-0.206414|	0.0512763|     0.0141986|	0.012944999999999998|	0.0480818862398944|	0.035407167156267794|

**Comment by francois-a** [comment]
Hi, that shouldn't be happening (even if the gene has only one independent signal it should be in the output). Does the number in the log match, i.e., are you expecting 399 or 400 genes in the output? Would it be possible to share the input files just for this gene?

**Comment by zpliu1126** [comment]
> Hi, that shouldn't be happening (even if the gene has only one independent signal it should be in the output). Does the number in the log match, i.e., are you expecting 399 or 400 genes in the output? Would it be possible to share the input files just for this gene?

After I filter the permute results according to FDR<0.05, in order to get the results faster; I run the module for each chromosome separately. for example there have 399 eGene in chr12, but in the result I only get 398 eGene which have multiple independent signals.

**Comment by francois-a** [comment]
The 399 genes appear to be correctly parsed. What happens if you subset the input to just the missing gene? Would you be able to share that data so that I can debug this?

**Comment by zpliu1126** [comment]
This is log of the missing gene 
```bash
  * WARNING: using CPU!
  * reading phenotypes (/data/cotton/zhenpingliu、eQTLgenes_Allstages_340samples/indepent_eQTL/GeneExpression/0DPA_AllSamples_370_FPKM_AllStages_norm_new.bed.gz)
  * reading covariates (/data/cotton/zhenpingliu/eQTLgenes_Allstages_340samples/peer_factor_num/0DPA/0DPA_covariate_peer_20.txt)
Mapping files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:11<00:00,  3.78s/it]
/public/home/zpliu/.local/lib/python3.6/site-packages/tensorqtl/genotypeio.py:146: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  self.bed = self.bed[:,ix]
cis-QTL mapping: conditionally independent variants
  * 370 samples
  * 1/1 significant phenotypes
  * 23 covariates
  * 2658921 variants
  * computing independent QTLs
    processing phenotype 1/1
Traceback (most recent call last):
  File "/public/home/software/opt/bio/software/Python/3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/public/home/software/opt/bio/software/Python/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/public/home/zpliu/.local/lib/python3.6/site-packages/tensorqtl/__main__.py", line 2, in <module>
    tensorqtl.main()
  File "/public/home/zpliu/.local/lib/python3.6/site-packages/tensorqtl/tensorqtl.py", line 146, in main
    logger=logger, seed=args.seed, verbose=True)
  File "/public/home/zpliu/.local/lib/python3.6/site-packages/tensorqtl/cis.py", line 855, in map_independent
    res_df = pd.concat(res_df, axis=0, sort=False)
  File "/public/home/zpliu/.local/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    sort=sort,
  File "/public/home/zpliu/.local/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```
By the way, do I need to share you the vcf file or just the permute output file?

**Comment by francois-a** [comment]
I'll need all the input files unless you can generate a different reproducible example, but only need the variants in the cis-window of this gene. And you can scramble the dosages (and the other inputs as well).

**Comment by zpliu1126** [comment]
the data and commands I used are stored in[ this repositories](https://github.com/HZAU-CottonLab/tensorQTL_testData/tree/cdb00e83f9eac6f6aa12c45decd9c152785fab38)。

**Comment by francois-a** [comment]
Thanks again for reporting this and providing the detailed example! This was a bug due to missingness, with the variants added to the covariates not being properly imputed (fixed in 2ae860fdb8aa99e7483f8bf4d33d001b952f2c56).

The TSS distance should be specified as a single position in the input BED file. I added a check for this in 639515b138f4adcacc2b2cc30e1ada93c45d05e8.

**Comment by zpliu1126** [comment]
Thank you very much for answering my questions patiently! I will have try the version of v1.0.6.

**Comment by zpliu1126** [comment]
> Thanks again for reporting this and providing the detailed example! This was a bug due to missingness, with the variants added to the covariates not being properly imputed (fixed in [2ae860f](https://github.com/broadinstitute/tensorqtl/commit/2ae860fdb8aa99e7483f8bf4d33d001b952f2c56)).
> 
> The TSS distance should be specified as a single position in the input BED file. I added a check for this in [639515b](https://github.com/broadinstitute/tensorqtl/commit/639515b138f4adcacc2b2cc30e1ada93c45d05e8).

I followed the prompts to modify the coordinates in the ![gene expression compressed file](https://github.com/HZAU-CottonLab/tensorQTL_testData/blob/39f8cb21bc30e5c2b90eff17081b0a84d763154e/test_gene_expression.bed.gz). It generated a new error

**Comment by francois-a** [comment]
This error is due to another change in v1.0.6, returning allele fraction ('af') instead of minor allele fraction ('maf') in the output files. This was done to for consistency, since the minor allele is not necessary the ALT/effect allele. As a workaround, you can rename the column from your input instead of re-running it (that column isn't used in this step, just checked for consistency).

**Comment by zpliu1126** [comment]
it works. thank you

**Comment by Junjun-Xu** [comment]
I have a question. My understanding is that each gene is independently analyzed for independent mode. Should my input file (--cis_output) include results for all genes, or only results for one gene? Would the identified loci be the same in both cases?

**Comment by francois-a** [comment]
The input for `--cis_output` should typically be all genes that pass FDR. You can provide the output from `cis` mode directly without prefiltering, since by default genes with FDR ≤ 0.05 (`qval` column) are selected.
