### ISSUE TITLE
TSS distance higher than the specified window for cis-eQTL analysis

### ISSUE THREAD

**Issue by elodiepersyn** [broadinstitute/tensorqtl#47]
Hi,
I was interested in TSS distances in cis eQTL results using tensorqtl.
Some values of `tss_distance` were <-1Mb or >1Mb, for example 23,163,540. The computation of the TSS distance is correct from looking at the position of the variant in the .bim file and the TSS. I am wondering what went wrong in my analysis. Could you please help me in understanding this ?
Thank you 
Elodie

**Comment by Yangxiaohan0120** [comment]
"def main():
    parser = argparse.ArgumentParser(description='tensorQTL: GPU-based QTL mapper')
    parser.add_argument('genotype_path', help='Genotypes in PLINK format')
    parser.add_argument('phenotype_bed', help='Phenotypes in BED format')
    parser.add_argument('prefix', help='Prefix for output file names')
    parser.add_argument('--mode', default='cis', choices=['cis', 'cis_nominal', 'cis_independent', 'trans'], help='Mapping mode. Default: cis')
    parser.add_argument('--covariates', default=None, help='Covariates file, tab-delimited, covariates x samples')
    parser.add_argument('--permutations', type=int, default=10000, help='Number of permutations. Default: 10000')
    parser.add_argument('--interaction', default=None, type=str, help='Interaction term')
    parser.add_argument('--cis_output', default=None, type=str, help="Output from 'cis' mode with q-values. Required for independent cis-QTL mapping.")
    parser.add_argument('--phenotype_groups', default=None, type=str, help='Phenotype groups. Header-less TSV with two columns: phenotype_id, group_id')
    parser.add_argument('--window', default=1000000, type=np.int32, help='Cis-window size, in bases. Default: 1000000.')
    parser.add_argument('--pval_threshold', default=None, type=np.float64, help='Output only significant phenotype-variant pairs with a p-value below threshold. Default: 1e-5 for trans-QTL')
    parser.add_argument('--maf_threshold', default=0, type=np.float64, help='Include only genotypes with minor allele frequency >= maf_threshold. Default: 0')
    parser.add_argument('--maf_threshold_interaction', default=0.05, type=np.float64, help='MAF threshold for interactions, applied to lower and upper half of samples')
    parser.add_argument('--return_dense', action='store_true', help='Return dense output for trans-QTL.')
    parser.add_argument('--return_r2', action='store_true', help='Return r2 (only for sparse trans-QTL output)')
    parser.add_argument('--best_only', action='store_true', help='Only write lead association for each phenotype (interaction mode only)')
    parser.add_argument('--output_text', action='store_true', help='Write output in txt.gz format instead of parquet (trans-QTL mode only)')
    parser.add_argument('--batch_size', type=int, default=20000, help='Batch size. Reduce this if encountering OOM errors.')
    parser.add_argument('--load_split', action='store_true', help='Load genotypes into memory separately for each chromosome.')
    parser.add_argument('--fdr', default=0.05, type=np.float64, help='FDR for cis-QTLs')
    parser.add_argument('--qvalue_lambda', default=None, type=np.float64, help='lambda parameter for pi0est in qvalue.')
    parser.add_argument('--seed', default=None, type=int, help='Seed for permutations.')
    parser.add_argument('-o', '--output_dir', default='.', help='Output directory')
    args = parser.parse_args()"

In the source code at the directory ./tensorqtl/tensorqtl.py, you can see one important argument "--window" which you can change your detection region from default 1000000 to any region you want. Hope it's useful.

**Comment by elodiepersyn** [comment]
Hi, 
I am using the 1Mb window. But I get few SNPs with a tss_distance higher than 1Mb. I am using the following command:
`cisnom_df = cis.map_nominal(genotype_df, variant_df, phenotype_df, phenotype_pos_df, cisnom_df_outprefix, covariates_df, window=1000000, maf_threshold=0.005)`
I get for example:
`phenotype_id,variant_id,tss_distance,af,ma_samples,ma_count,pval_nominal,slope,slope_se
ENSG00000028137,rs587669835,1096141,0.994172,53,56,0.3039955479904355,0.046624605,0.045353957`

**Comment by francois-a** [comment]
Hi, could you please provide an example dataset that reproduces this issue?
