### ISSUE TITLE
tensorQTL using CPU on a GPU host

### ISSUE THREAD

**Issue by Toseph** [broadinstitute/tensorqtl#5]
Hello, I am writing on behalf of one of my users at our facility. 

We are trying to run tensorQTL on a test dataset, and have tensorflow working with cuda and gpu resources but tensorQTL presents this warning message: 
`[Nov 04 14:38:47] Running TensorQTL: cis-QTL mapping
  * WARNING: using CPU!`

This setup is using the following modules/resources
`[root@pe2dg2-01 local]# python --version
Python 3.7.1rc1
[root@pe2dg2-01 local]# pip freeze | grep tensor
tensorboard==2.0.0
tensorflow-estimator==2.0.1
tensorflow-gpu==2.0.0
tensorqtl==1.0.1
NVIDIA-SMI 410.48
Driver Version: 410.48
0  Tesla V100-PCIE
1  Tesla V100-PCIE`

Can you recommend any changes to our setup or modules that are necessary to use GPU compute with tensorqtl?

**Comment by francois-a** [comment]
Hi,

Have you followed the installation instructions listed at https://github.com/broadinstitute/tensorqtl/tree/master/install? Recent versions of tensorQTL use PyTorch instead of TensorFlow. What output do you get from `nvidia-smi`?

**Comment by Toseph** [comment]
This is my nvidia-smi output, I usually rely on environment modules to load cuda to the appropriate env variables. 

`[thasan@pe2dg2-01 ~]$ nvidia-smi
Wed Nov  6 13:06:27 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   31C    P0    25W / 250W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:D8:00.0 Off |                    0 |
| N/A   33C    P0    25W / 250W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+`

**Comment by Toseph** [comment]
I'll try installing pytorch against the python install and see if that works and use the install guide linked above.

**Comment by Toseph** [comment]
Updating the machine to the latest drivers allowed tensorqtl to successfully run the test bench using the gpus. We noted that cuda 10.0 and cuda 10.1 both work against this driver and with tensorqtl. 

`| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |`

**Comment by francois-a** [comment]
Great, thanks for the update!
