### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by guandailu** [broadinstitute/tensorqtl#52]
I am wondering if tensorQTL can handle missing values (e.g. NA) for phenotype?

**Comment by francois-a** [comment]
You'll need to impute the missing values (e.g., with the mean, or half-minimum value, etc., before inverse normal transform). The appropriate imputation will depend on the phenotypes -- what are your phenotypes?

**Comment by Geneva0725** [comment]
Hi, I have the same problem and I'm going to discovery eQTL from single cell RNA-seq dataset based on droplet platform. There are many NAs in my data, like 10% NA within a single feature(gene), and I'm wondering which imputation method should be appropriate, btw, there are around 400 samples in my data.
And I'm wondering what if I make NA to be 0 after inverse normal transform, is that OK?

Thanks!
