### ISSUE TITLE
Can't run trans-qtl analysis without interaction

### ISSUE THREAD

**Issue by llandsmeer** [broadinstitute/tensorqtl#59]
These pieces don't work for `interaction = None`

 - `if interaction_df.shape[1] > 1:`
 - `interaction_s=interaction_df.squeeze('columns')`

**Comment by francois-a** [comment]
Thanks for reporting this! Fixed in 97d6f26eae9c2d8624214c4e15b52c528e823001.

**Comment by llandsmeer** [comment]
Np, thanks for publishing this package and handling the issue so fast!
