### ISSUE TITLE
Set number of permutations fails

### ISSUE THREAD

**Issue by snesic** [broadinstitute/tensorqtl#6]
Hi, 

I managed to run tensorQTL successfully from a docker container (using your dockerfile) but soon as I added permutations (e.g. --permutations 100) it failed with the following error: 

permutation_ix_t = torch.LongTensor(np.array([np.random.permutation(ix) for i in range(nperm)])).to(device)
TypeError: 'str' object cannot be interpreted as an integer

It also failed to build docker image from your docker file as Bioconductor changed the way to install libraries. When I updated that line (47 I think) I managed to create a docker image. 

Hope this helps, 
Thanks,

**Comment by francois-a** [comment]
Hi,

Thanks for catching this issue. It's fixed in the latest commit. The Dockerfile is fixed as well.

**Comment by snesic** [comment]
Excellent, thanks!
