### ISSUE TITLE
Interaction p-values

### ISSUE THREAD

**Issue by ariadnacilleros** [broadinstitute/tensorqtl#60]
Hi, 
I am performing some interaction nominal cis-QTL mapping analyses, but I noticed that I get three different p-values considering the statistical model performed (p ~ g + i + gi). My question is the following, do I have to take into account all three p-values for considering a QTL true? Or just one of them?

Thanks!

**Comment by francois-a** [comment]
Hi, please see the Supplementary Materials of https://www.science.org/doi/10.1126/science.aaz8528 for details on how to evaluate the results from the interaction model.
