### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by llandsmeer** [broadinstitute/tensorqtl#62]
This is probaly out of scope of the project, still I think it would be a nice addition.

For trans-mQTL analysis I'm running out of memory on our RTX6000 instance. Of course just subsetting the datasets manually solves that (although I don't know how large my input files can be..), but it would be much nicer if the computation could just run by utilizing all 4 RTX6000's connected to the node. In pure CUDA this should be possible with managed memory, but I'm not sure if this is mapped through to PyTorch (which the project seems to use). I think the setup uses two pairs of NVLink connections, but plain PCIe communication is also available of course

So would this something that could be considered for the future? Or is this out of scope for the project?

**Comment by francois-a** [comment]
I think this should be doable, but don't have much bandwidth to look into it at the moment. That said, you should be able to get around this by decreasing batch size with `--batch_size`, with little loss of performance.

**Comment by JMencius** [comment]
Hi @francois-a  I am re-checking this issue on July of 2025, is it still not supported for multi-GPU?
