### ISSUE TITLE
coloc qnorm method

### ISSUE THREAD

**Issue by ChristopherWilks** [broadinstitute/tensorqtl#63]
Hi,

First, thanks for a great improvement on FastQTL and related!

While I know that colocalization wasn't part of the tensorQTL publication, I was still curious about the `coloc.py` script you include in the repo here.  I was looking for a python/gpu replacement for the approximate bayes factors method in R from https://github.com/chr1swallace/coloc.

Is the coloc.py script supposed to be a tensor version of that method?

If it is, the equivalent of the `qnorm` method in R from

https://github.com/chr1swallace/coloc/blob/29e45d11e499a0c1d6bee74e9205df92a81dc72d/R/claudia.R#L75

should be `scipy.stats.norm.ppf` not `scipy.stats.norm.isf` as it is here:

https://github.com/broadinstitute/tensorqtl/blob/e71a404d265abfd3f6af0ac3f8ff8c16d15edb87/tensorqtl/coloc.py#L64

Of course, if the intent here was something else, please disregard this issue.

Thanks,
Chris

**Comment by nmra-cwilks** [comment]
Thanks for the response!
My mistake, I had seen differences between the R COLOC's output and my adaptation of the `coloc.py` for a different use case and thought I had tracked it down to that function, but now I think it's very likely something I changed when updating the code.
