### ISSUE TITLE
QTL interaction

### ISSUE THREAD

**Issue by guandailu** [broadinstitute/tensorqtl#64]
I am running interaction QTL using command:
python3 -m tensorqtl ${genotype} ${phenotype} ${prefix} \
    --covariates ${covariates} \
    --interaction ${interaction} \
    --mode cis_nominal \
    --maf_threshold 0.05 \
    --maf_threshold_interaction 0.05 #--best_only

Some of them are failed, because of errors below:
.local/lib/python3.6/site-packages/tensorqtl/core.py:52: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at  /pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp:1940.)
  self.Q_t, _ = torch.qr(C_t - C_t.mean(0))
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dguan/.local/lib/python3.6/site-packages/tensorqtl/__main__.py", line 2, in <module>
    tensorqtl.main()
  File "/home/dguan/.local/lib/python3.6/site-packages/tensorqtl/tensorqtl.py", line 122, in main
    write_top=True, write_stats=not args.best_only, logger=logger, verbose=True)
  File "/home/dguan/.local/lib/python3.6/site-packages/tensorqtl/cis.py", line 272, in map_nominal
    ix = np.nanargmax(np.abs(tstat[:,2]))
  File "<__array_function__ internals>", line 6, in nanargmax
  File "/share/apps/bio3user/miniconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py", line 549, in nanargmax
    raise ValueError("All-NaN slice encountered")
ValueError: All-NaN slice encountered

Do you know what happend?
Thanks in advance!

**Comment by francois-a** [comment]
Hi, can you please update to the latest version from this repo (I'll push a new release soon). It looks like this error arose because all associations for the phenotype are returning NaN. Are there any missing/NaN values in your phenotypes?

**Comment by curryfly5** [comment]
> I am running interaction QTL using command: python3 -m tensorqtl ${genotype} ${phenotype} ${prefix} --covariates ${covariates} --interaction ${interaction} --mode cis_nominal --maf_threshold 0.05 --maf_threshold_interaction 0.05 #--best_only
> 
> Some of them are failed, because of errors below: .local/lib/python3.6/site-packages/tensorqtl/core.py:52: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release. The boolean parameter 'some' has been replaced with a string parameter 'mode'. Q, R = torch.qr(A, some) should be replaced with Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at /pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp:1940.) self.Q_t, _ = torch.qr(C_t - C_t.mean(0)) Traceback (most recent call last): File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/usr/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/dguan/.local/lib/python3.6/site-packages/tensorqtl/**main**.py", line 2, in tensorqtl.main() File "/home/dguan/.local/lib/python3.6/site-packages/tensorqtl/tensorqtl.py", line 122, in main write_top=True, write_stats=not args.best_only, logger=logger, verbose=True) File "/home/dguan/.local/lib/python3.6/site-packages/tensorqtl/cis.py", line 272, in map_nominal ix = np.nanargmax(np.abs(tstat[:,2])) File "<**array_function** internals>", line 6, in nanargmax File "/share/apps/bio3user/miniconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py", line 549, in nanargmax raise ValueError("All-NaN slice encountered") ValueError: All-NaN slice encountered
> 
> Do you know what happend? Thanks in advance!

hi, i have met the same problems while running  interaction eQTL mapping, have you fixed this problem?I would appreciate a reply.
