### ISSUE TITLE
Inconsistent tss_distance in cis.map_nominal and cis.map_independent

### ISSUE THREAD

**Issue by anglixue** [broadinstitute/tensorqtl#65]
First, thanks for providing such a wonderful tool.

I followed the pipeline to calculate the nominal p-value, permutation, and conditionally independent QTLs. However, in the results of independent QTLs, I found the column "tss_distance" is inconsistent with the previous step. Please see the example below.

In cis.map_independent
```
>>> indep_df.head()
  phenotype_id  num_var  beta_shape1  beta_shape2     true_df  pval_true_df  \
0        NFAM1     3470     0.979389   115.244293  756.459656  8.011556e-07
1        RIBC2     5409     1.047371   540.275879  819.908508  4.425710e-08

    variant_id  tss_distance  ma_samples  ma_count        af  pval_nominal  \
0  22:42515637         39941         533       627  0.319898  2.699133e-08
1  22:45774531         69681         226       237  0.120918  3.173554e-09

      slope  slope_se  pval_perm  pval_beta  rank
0 -0.018384  0.003279     0.0004   0.000113     1
1  0.006227  0.001042     0.0001   0.000014     1
```

The tss_distance for variant 22:42515637 of gene NFAM1 is 39941.

While in the cis.map_nominal, the distance is -260780.
```
pairs_df.loc[(pairs_df["phenotype_id"]=="NFAM1") & (pairs_df["variant_id"]=="22:42515637"),:]
        phenotype_id   variant_id  tss_distance        af  ma_samples  \
1075789        NFAM1  22:42515637       -260780  0.319898         533

         ma_count  pval_nominal     slope  slope_se
1075789       627      0.737578 -0.000178  0.000532

```

This doesn't make sense to me since they both were generated from the same set of input files. 

I checked the input location of this gene and it is 
`chr22	42776416	42776417	NFAM1`

So the distance in cis.map_nominal should be the right one, i.e.,  42515637 - 42776417 = -260780

Any thoughts/suggestions will be appreciated!

**Comment by francois-a** [comment]
Hi, I'm not able to reproduce this. Can you please check if this still occurs with v1.0.7?

**Comment by anglixue** [comment]
Hi Francois,

Thanks for your reply.

Just upgraded to v1.0.7 but encountered an error when importing the mixqtl.py from the tensorqtl. It seems to be a minor import syntax error in line#59 of mixqtl.py induced by a typo I believe. 

I've tested it on my machine and after removing the asterisk it's good to run. I've submitted a pull request for you to review. 

Unfortunately, the inconsistency of tss_distance between cis.map_nominal and indep_df was still there.

**Comment by anglixue** [comment]
Hi @francois-a ,

I have used v1.0.7 and re-ran all the analyses. I found that there are always ~10% variants that showed inconsistent results between cis.map_nominal() and cis_df().

Here is the example for chromosome 22 in my data. I tested 408 genes and 69805 variants. After matching nominal associations with significant associations, 43 / 408 eQTLs showed inconsistent pval_nominal, slope/slope_se, tss_distance. The allele freq, ma_samples, ma_count.

Nominal associations:

```
head(nom[index, -1])
    phenotype_id  variant_id tss_distance         af ma_samples ma_count pval_nominal         slope     slope_se                   pair
102         DDTL 22:24266726       -42364 0.38367346        603      752 3.084511e-34  0.0054795183 0.0004317051       22:24266726_DDTL
103   KB-226F1.2 22:24267047       -44354 0.38265306        602      750 4.183513e-07  0.0009024401 0.0001770988 22:24267047_KB-226F1.2
104          DDT 22:24245292       -68263 0.33214286        525      651 2.866474e-19 -0.0525704920 0.0057343070        22:24245292_DDT
136         HSCB 22:28339553      -798467 0.15306123        263      300 7.034724e-01  0.0009122025 0.0023957987       22:28339553_HSCB
137      CCDC117 22:28303075      -865588 0.05408163        104      106 1.195958e-01 -0.0037228062 0.0023896908    22:28303075_CCDC117
138         XBP1 22:28629713      -560831 0.16938776        296      332 1.304909e-30  0.1073389800 0.0090110050       22:28629713_XBP1
```

Significant associations:
 
```
head(sig[index,colnames(nom)[-1]])
    phenotype_id  variant_id tss_distance         af ma_samples ma_count pval_nominal        slope     slope_se                   pair
102         DDTL 22:24266726       -46829 0.38367346        603      752 9.790065e-49 -0.082714660 0.0053232773       22:24266726_DDTL
103   KB-226F1.2 22:24267047       -42043 0.38265306        602      750 2.517564e-34  0.005490042 0.0004319025 22:24267047_KB-226F1.2
104          DDT 22:24245292       -66109 0.33214286        525      651 1.776509e-08  0.001006383 0.0001771545        22:24245292_DDT
136         HSCB 22:28339553      -940028 0.15306123        263      300 3.107622e-04  0.001176659 0.0003251019       22:28339553_HSCB
137      CCDC117 22:28303075      -834945 0.05408163        104      106 2.647748e-03  0.012170344 0.0040382070    22:28303075_CCDC117
138         XBP1 22:28629713      -538950 0.16938776        296      332 1.030225e-04  0.005427211 0.0013917054       22:28629713_XBP1
```

And if I plot the pval_nominal between the two results, it looks like this
![Rplot_chr22_CD4_NC](https://user-images.githubusercontent.com/8247682/180127349-139a1016-e700-41f7-bce8-26dc7603cd29.png)

Hope to get some advice from you on how I can dig into and solve the problem.

Thank you!

Cheers,
Angli

**Comment by francois-a** [comment]
Hi, I'm unable to reproduce this. The TSS distances between the different modes (cis permutations, nominal, independent) are consistent in my tests. Do you have duplicate gene symbols in your inputs? Otherwise, can you share a small subset of your dataset that reproduces the problem?
