### ISSUE TITLE
Approximate the adjusted P-value from the best nominal P-value

### ISSUE THREAD

**Issue by anglixue** [broadinstitute/tensorqtl#66]
Hi, I was trying to understand the output of column "pval_true_df"

From the equation (5) of the fastQTL paper, the beta-approximated p-value (pb) from the best nominal p-value (pn) should be

> pb = P( U <= on)

so the pb can be calculated by

> pb = pbeta(pn, shape1, shape2)

, where pn is the best nominal p-value and shape1 and shape2 are from the estimates in the output.

However, when I looked at my output, this equation doesn't hold. Take the first row as an example,

> pbeta(q = 2.718580e-05, shape1 = 1.046623, shape2 = 196.4767) = 0.004089984

, not the same as pval_beta (0.015221135)

But if I put pval_true_df in the equation then it equals to the pval_beta.

> pbeta(q = 9.604937e-05, shape1 = 1.046623, shape2 = 196.4767) = 0.015221135

I wonder why the input would be pval_true_df. It is the pval for the degree of freedom rather than the nominal pval.

Thanks for your time!

```
> head(a)
  phenotype_id num_var beta_shape1 beta_shape2  true_df pval_true_df
1       TPTEP1    1861    1.046623    196.4767 829.6173 9.604937e-05
2        CECR7    2984    1.030993    285.0457 841.2630 2.472956e-03
3  AC006946.16    3076    1.039961    311.8832 846.1926 1.316065e-03
4       IL17RA    3105    1.025234    295.1855 835.6140 2.449269e-05
5        CECR5    3192    1.056958    313.2942 838.2010 4.435101e-04
6    CECR5-AS1    3243    1.042489    347.3976 851.3823 5.196592e-03
   variant_id tss_distance ma_samples ma_count         af pval_nominal
1 22:17075476        -7302        158      163 0.08316327 2.718580e-05
2 22:17074427      -443034        123      125 0.06377551 1.223717e-03
3 22:17653030       104318        703      909 0.46377552 6.221093e-04
4 22:17601466        35621        552      664 0.33877552 6.104075e-06
5 22:17640022        21620        155      157 0.08010204 1.702889e-04
6 22:17626236       -14039        264      295 0.15051020 3.001338e-03
         slope     slope_se  pval_perm   pval_beta        qval
1  0.006163854 0.0014619246 0.01259874 0.015221135 0.016499875
2 -0.002757097 0.0008501779 0.49475052 0.491443179 0.217732235
3 -0.000745052 0.0002170173 0.32386761 0.318164792 0.163471594
4  0.011115639 0.0024439932 0.00599940 0.006292479 0.008225463
5 -0.014338480 0.0037989614 0.11508849 0.112874603 0.082240148
6  0.001332406 0.0004478379 0.83041696 0.825385224 0.286859862
```

**Comment by francois-a** [comment]
Hi, `pval_true_df` is not the p-value for degrees of freedom. Rather, it is the p-value computed using an estimate of the true degrees of freedom, computed [here](https://github.com/broadinstitute/tensorqtl/blob/master/tensorqtl/core.py#L336). The details of the derivation are in [Galwey, 2009](https://pubmed.ncbi.nlm.nih.gov/19217024/) (cited in the FastQTL paper).

**Comment by anglixue** [comment]
That makes sense now. Thank you!
