### ISSUE TITLE
sQTL analysis TSS

### ISSUE THREAD

**Issue by rgarcia27** [broadinstitute/tensorqtl#70]
hey, I'm trying to run tensorqtl to identify sqtls. The phenotype files I have are form leafcutter, but I notices that the end is not start+1 so I'm getting this error.

`The BED file must define the TSS/cis-window center, with start+1 == end.`

I'm gonna correct it manually but I'm not sure if a should just leave the start position as it is or take the middle point between start and end as the start (and then correct the end value of course). Could you help me with this please?

**Comment by francois-a** [comment]
It's now possible to define cis-windows based on either a single position/TSS (if `start+1 == end` in the BED file) or with different start/end positions, in which case the cis-window is [start-window, end+window].
