### ISSUE TITLE
Which is the effect allele?

### ISSUE THREAD

**Issue by ariadnacilleros** [broadinstitute/tensorqtl#72]
Hi, 

I have been conducting some mQTLs mapping using the nominal approach from Tensor. But I have question, which is the allele tested for the effect, p-value and standard error reported in the results? 

Thanks! 

Ariadna

**Comment by Hiroaki-S-Ri** [comment]
Hi, is the effect allele minor allele of plink bed?

**Comment by francois-a** [comment]
Hi, tensorQTL requires alleles to be encoded as REF/ALT. The default encoding of alleles as minor/major is a common issue with PLINK 1, see [here](https://www.cog-genomics.org/plink/1.9/data#ax_allele) and [here](https://github.com/broadinstitute/tensorqtl/blob/master/tensorqtl/genotypeio.py#L137).
