### ISSUE TITLE
Expected format for --interaction parameter

### ISSUE THREAD

**Issue by kauralasoo** [broadinstitute/tensorqtl#74]
Hi Francois,

Could you clarify the expected file format for the --interaction parameter when performing interaction tests? I tried to use the exact same format as the [example](https://personal.broadinstitute.org/francois/geuvadis/GEUVADIS.445_samples.covariates.txt) covariates file, but got the following error:

> Traceback (most recent call last):
>  File “/usr/lib/python3.8/runpy.py”, line 194, in _run_module_as_main
>   return _run_code(code, main_globals, None,
>  File “/usr/lib/python3.8/runpy.py”, line 87, in _run_code
>   exec(code, run_globals)
>  File “/usr/local/lib/python3.8/dist-packages/tensorqtl/__main__.py”, line 2, in <module>
>   tensorqtl.main()
>  File “/usr/local/lib/python3.8/dist-packages/tensorqtl/tensorqtl.py”, line 80, in main
>   assert covariates_df.index.isin(interaction_df.index).all()
> AssertionError

Best,
Kaur

**Comment by kauralasoo** [comment]
Ok, I think I figured it out. The relevant part of the source code is here:
https://github.com/broadinstitute/tensorqtl/blob/master/tensorqtl/tensorqtl.py#L75-L78

I will test it and post an example later. Will close the issue then.

**Comment by francois-a** [comment]
Hi Kaur,
Yes, the input should be a TSV with two columns (header optional) for a single interaction term, mapping participant IDs to values, or a TSV with header and multiple columns for multiple interaction terms.

**Comment by cora97846** [comment]
Hi Francois,
Now I am doing the eqtl of gender differences, I add the genotype, expression amount, and covariates (the covariates do not include gender), and I can directly divide gender into 1 and 2 and put them in the --interaction.
Best,
Kaur

**Comment by cora97846** [comment]
Hi Francois,
Now I am doing the eqtl of gender differences, I add the genotype, expression amount, and covariates (the covariates do not include gender), and I can directly divide gender into 1 and 2 and put them in the --interaction.
Best,
cora
