### ISSUE TITLE
How to use Plink2 files including multiallelic file

### ISSUE THREAD

**Issue by kendaida** [broadinstitute/tensorqtl#75]
Hi,
I would like to use plink2 pfiles including multialleclic variants.
I installed pgenlib but it could not run at 'genotypeio.PlinkReader".

pr = genotypeio.PlinkReader(pfile_prefix_path)

I think plink bfile can not include multiallelic variants.
Would you tell me how to solove it?

**Comment by francois-a** [comment]
Hi,
Multi-allelic variants are [not fully supported in the API](https://github.com/chrchang/plink-ng/blob/master/2.0/Python/python_api.txt#L88). I recommend splitting multiallelic sites instead, using `bcftools norm` for example.

**Comment by kendaida** [comment]
I got it. I appreciate you.
