### ISSUE TITLE
An error in tensorqtl_examples.ipynb ?

### ISSUE THREAD

**Issue by taeyoungh** [broadinstitute/tensorqtl#76]
Hi, I am testing tensorqtl_examples.ipynb and had an error in line 3 "cis-eQTL: nominal p-values": `cis.map_nominal(genotype_df, variant_df, phenotype_df, phenotype_pos_df, covariates_df, prefix)`. But, it seems that the argument locations of covariates_df and prefix are different from the definition. Should it be `cis.map_nominal(genotype_df, variant_df, phenotype_df, phenotype_pos_df, prefix, covariates_df)` ?

**Comment by francois-a** [comment]
Hi, that's correct, thanks for pointing this out. Fixed [here](https://github.com/broadinstitute/tensorqtl/blob/master/example/tensorqtl_examples.ipynb).
