### ISSUE TITLE
Reproduce GTEx v8

### ISSUE THREAD

**Issue by gaotc200** [broadinstitute/tensorqtl#77]
Hi,

I'm trying to reproduce the GTEx v8 cis-eQTL but notice several inconsistency between my run and the GTEx Analysis V8 (dbGaP Accession phs000424.v8.p2). For example, in ovary, the number of common eGenes between my run and GTEx is **5368** out of total **5542** GTEx egene (96.9%). For common eGene-eVariant pairs the number is **4723/5542**.

I'm using `tensorQTL v1.0.5` and following this [code](https://github.com/broadinstitute/gtex-v8/blob/master/analyses/GTEx_v8_QTL_mapping.ipynb). I wrote an email to  regrading this problem a few days ago, but haven't here back yet, so I'm posting here to try some luck. Sorry for the duplication.

After sending my email, I look deeper into the problem and notice several things that might be potential reasons.
1. There are several genes that have **different TSS** (or gene start position) in `GTEx_Analysis_v8_eQTL_expression_matrices.tar` and in the final eQTL file `GTEx_Analysis_v8_eQTL.tar`. 

- For example, gene ENSG00000272512.1 start at 998050 in the expression file, but 995966 in the eQTL file.

2. There are SNPs that have **different nominal result** in the sig_pair file in `GTEx_Analysis_v8_eQTL.tar` and in my nominal run parquet file. 
- For example, for gene ENSG00000237973.1 in ovary:

| Data | SNP  | Nominal P-value |
| ----- | -------- | ------------- |
|GTEX| chr1_992917_G_A_b38 |  25e-6 |
|GTEX| chr1_1598099_C_G_b38 |  4e-6 |
|Reproduce| chr1_992917_G_A_b38 |  8e-6 |
|Reproduce| chr1_1598099_C_G_b38 |  15e-6 |

The SNPs have same maf, ma_samples, ma_count and tss_distance between "GTEX" and "Reproduce", but different slope and p-nominal and all downstream stats. I could imagine there might be small changes in the p-value due to the precision of float or technical reason, but here the order is filpped, which seems to be a big issue. Based on my understanding, the nominal run is a simple linear regression without any randomness. It should not change if the input (genotype, expression, covariates) remain the same.

3. The above two together seems to suggest that it is because of different file versions. Again I'm using those files indicated in this [code](https://github.com/broadinstitute/gtex-v8/blob/master/analyses/GTEx_v8_QTL_mapping.ipynb).

Hope you can help explain some of these problems. Thank you very much.

Best,
Jiahao

**Comment by francois-a** [comment]
Hi, please take a look at this [notebook](https://github.com/broadinstitute/tensorqtl/blob/master/example/GTEx_v8_example.ipynb), which shows how to reproduce the V8 results. Aside from minor differences close to the FDR threshold due to the random seed, the results should be identical.

ENSG00000272512.1 is on the - strand, meaning that the TSS is the end position (998051). The phenotype matrix is in BED format (0-based), so 998050 is correct.

**Comment by gaotc200** [comment]
Thank you for the explanation of the TSS.

Regarding the main problem, when I follow your new example code, I'm able to reproduce your result in that notebook. With this example, when looking at the eGene-eVariant pairs, the overlap is around 8720/9082 (96%), so I will assume this level of inconsistency is simply due to randomness.

However, your new example is essentially the exact same code as the one I'm previously following (the part that do nominal and permutation run), with a given random seed. In fact, my previous run of the brain cortex has almost identical result as the new one following your new example. Thus, I would assume my previous run for **ovary** is correct as well, but the inconsistency is much greater. Actually, I notice that this reproduction percentage vary a lot in different tissues.

My main purpose of re-do GTEx is because I want to run the GTEx pipeline with some different parameter, and need a comparable (e.g. using the same tool tensorQTL) baseline. Given the above, I think I'm still running things in the correct setting, so they are valid baseline. What do you think about this?

Best regards,
Jiahao

**Comment by francois-a** [comment]
Ovary has 5542 eGenes (you can see this [here](https://gtexportal.org/home/tissueSummaryPage), for example).

When comparing results, you also need to take into account LD. The overlap should be >99%. In the notebook I shared above, you can see that the nominal p-values for the lead variant of each gene are identical between the FastQTL and TensorQTL runs, suggesting that they are in perfect LD. There may be multiple variants in perfect LD for a given gene, and which among these is selected as the representative lead variant may differ between the FastQTL and TensorQTL outputs.
