### ISSUE TITLE
Interaction mode: k variable overwrite in cis.py script (v1.0.7)

### ISSUE THREAD

**Issue by KrotosBenjamin** [broadinstitute/tensorqtl#78]
Hello,

Thank you for developing the tensorqtl software as it has dramatically decreased the time it takes to run eQTL analysis. I was running an interaction analysis in script (see example code below) and ran into a TypeError (see Traceback below). I was able to troubleshoot this issue and found that it was an accidental overwrite of the variable k -- keeping track of the chromosome number. This bug does not appear in version 1.0.6 as this seems to be specific to increasing the number of interactions allowed in the software (from the previous vector to the matrix format, which is greatly appreciated!).

A simple solution would be to replace the 'k' variable in three for loops starting on lines 446, 450, and 452 (cis.py).

This was a total of 9 replaces and solved the TypeError. This was so simple I wasn't sure if it made sense for a pull request. This issue doesn't effect anything else, so it would be easy to miss as interaction model are rare use cases.

Thanks again for the hard work in creating this software.
KJ

------------------------
    cis.map_nominal(genotype_df, variant_df, phenotype_df, phenotype_pos_df,
                    prefix, covariates_df=get_covars(args.feature),
                    interaction_df=get_interaction(), maf_threshold=0.01,
                    window=500000, maf_threshold_interaction=0.05,
                    output_dir=".", run_eigenmt=True,
                    write_top=True, write_stats=True)
-------------------------
> Traceback (most recent call last):
>    File "../_h/eqtl_tensorqtl.py", line 62, in <module>
>      main()
>    File "../_h/eqtl_tensorqtl.py", line 55, in main
>      write_top=True, write_stats=True)
>    File "/users/jbenjami/.local/lib/python3.7/site-packages/tensorqtl/cis.py", line 250, in map_nominal
>      for k, (phenotype, genotypes, genotype_range, phenotype_id) in enumerate(igc.generate_data(chrom=chrom, verbose=verbose), k+1):
> TypeError: can only concatenate str (not "int") to str
------------------------
The issue appears to be from the

**Comment by francois-a** [comment]
Hi, thanks for reporting this! Fixed in 6879d887db13d880fc5fc0619906c4fbdbbb2843.
