### ISSUE TITLE
missing pval_nominal_threshold column in output cis_qtl.txt file

### ISSUE THREAD

**Issue by jeoneunyoung** [broadinstitute/tensorqtl#80]
We are having such a great time using tensorqtl. Thanks for the wonderful tool. 

I am currently having trouble with missing pval_nominal_threshold column in my output cis_qtl.txt file when running in --mode cis. Other columns are appearing just fine, but the pval_nominal_threshold column. 

If I run with the same --mode cis command with different expression bed file, I get the pval_nominal_threshold column. 

Do you possibly know why this is happening?

Sincerely,

Leah

**Comment by jeoneunyoung** [comment]
Nevermind :) There were no signals below qval 0.05!

**Comment by CuteGold0407** [comment]
hi，i met the same issue(;_;)，when i run the same code on different phenotype files, like chr2 and chr3, the outfile of chr3 have the pval_nominal_threshold column, but chr2 didn't. do you know how to fix that?

**Comment by francois-a** [comment]
If you're running tensorqtl on subsets of phenotypes, you'll need to combine the outputs first, and then compute q-values on the combined output, using `post.calculate_qvalues`. See [here](https://github.com/broadinstitute/tensorqtl/blob/master/tensorqtl/tensorqtl.py#L172) for example.
