### ISSUE TITLE
Output Documentation

### ISSUE THREAD

**Issue by idinsmore1** [broadinstitute/tensorqtl#81]
Hi there,

It looks like the documentation for FastQTL that you link to no longer exists on sourceforge.net. Could you provide output documentation for tensorqtl? Thanks!

**Comment by baishengjun** [comment]
Hi,
Have the same issue, I can not find the output documentation for FastQTL, Could you provide output documentation for tensorqtl? 
Thanks in advance

**Comment by baishengjun** [comment]
Can anyone help us?
Thanks a lot

**Comment by francois-a** [comment]
Hi, thanks for pointing out the missing documentation, now added [here](https://github.com/broadinstitute/tensorqtl/blob/master/docs/outputs.md).
