### ISSUE TITLE
TensorQTL load Plink2 files in command line

### ISSUE THREAD

**Issue by alicewang19** [broadinstitute/tensorqtl#82]
To whom it may concern,

I am currently using your tensorQTL tool in command line CPU mode, and I encountered a problem while trying to load Plink2 files (dosage imputed). It is currently giving me a file not found error while I put all the pgen/psam/pvar in one folder and excluding bed/bim/fam files in the genotype directory.

I saw that your team make several updates to the genotypeio.py file. Do you have suggestions on how to correctly load the Plink2 dosage imputed genotype files in the command line? (put Plink1.9 and Plink2 files in the same folder or separate?) Thanks a lot in advance!

**Comment by francois-a** [comment]
Hi, there shouldn't be any errors in either of these configurations. If both pgen/psam/pvar and bed/bim/fam files are present in the same directory, the former will be used. If you're using Plink2 files, you don't need the Plink1.9 ones.
