### ISSUE TITLE
Cannot run cis.map_independent

### ISSUE THREAD

**Issue by idinsmore1** [broadinstitute/tensorqtl#84]
Hi there,

I'm having some issues running the `map_independent` function after successfully running `map_cis` and `calculate_qvalues` on my data. My output looks like this: 

```
indep_df = cis.map_independent(genotype_df, variant_df, cis_df, phenotype_df, phenotype_pos_df, covariates_df)
indep_df.to_csv('fz175_out/fz175_independent_significant_results.csv')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [29], line 1
----> 1 indep_df = cis.map_independent(genotype_df, variant_df, cis_df, phenotype_df, phenotype_pos_df, covariates_df)
      2 indep_df.to_csv('fz175_out/fz175_independent_significant_results.csv')

File ~/miniforge3/envs/tensorqtl/lib/python3.8/site-packages/tensorqtl/cis.py:762, in map_independent(genotype_df, variant_df, cis_df, phenotype_df, phenotype_pos_df, covariates_df, group_s, maf_threshold, fdr, fdr_col, nperm, window, random_tiebreak, logger, seed, verbose)
    760 igc = genotypeio.InputGeneratorCis(genotype_df, variant_df, phenotype_df, phenotype_pos_df, group_s=group_s, window=window)
    761 if igc.n_phenotypes == 0:
--> 762     raise ValueError('No valid phenotypes found.')
    763 logger.write('  * computing independent QTLs')
    764 start_time = time.time()

ValueError: No valid phenotypes found.

```

However, when looking at the intersection of the phenotype_df, phenotype_pos_df, and cis_df (my cis.map_cis result dataframe with qvals), there are no mismatched phenotypes. Any help would be greatly appreciated, thanks!

**Comment by francois-a** [comment]
Hi, this error is currently raised when `cis_df` contains no phenotypes with q-value ≤ 0.05 (default). I added a more explicit error in c41d546a6dc6c1cff107a78deeae433cbb0fbc87.

**Comment by idinsmore1** [comment]
@francois-a Thanks for getting back to me, but this is not true. From the above output, I'm also getting the following log 
```
cis-QTL mapping: conditionally independent variants
  * 2225 samples
  * 4858/5000 significant phenotypes
  * 71 covariates
  * 3130722 variants
```
And, when looking at qvalues directly, I can confirm this is true. What's strange is that if I run `map_independent` directly on the object returned from `map_cis`, it runs. However, if I save the output of `map_cis` to a file, then read in the dataset  from the file, it no longer works.

**Comment by francois-a** [comment]
It sounds like an issue with writing/reading the file then? Can you please post a reproducible example?

**Comment by idinsmore1** [comment]
I played around with the files a little bit, it seems that by setting the phenotype_id to be the index, things seem to running now. Is it possible to filter the snps that you want to test for conditional independence? I have ~3 million snps in my genetic set, but I'm particularly interested in about 300 of them. Can I filter down my results from cis.map_cis to only test the independence of those 300? Thanks for your help!
