### ISSUE TITLE
TypeError of interaction mode when removing the command "--best-only"

### ISSUE THREAD

**Issue by RL-m** [broadinstitute/tensorqtl#85]
Hi tensorqtl developers!

I've met a TypeError when running the interaction mode. I used the same format of inputs as your examples. Af first I used the command as is on GitHub and the results were fine:
`python3 -m tensorqtl ${plink_prefix_path} ${expression_bed} ${prefix} \
    --covariates ${covariates_file} \
    --interaction ${interactions_file} \
    --best_only \
    --mode cis_nominal`
However, when I removed the "--best-only" command:
`python3 -m tensorqtl ${plink_prefix_path} ${expression_bed} ${prefix} \
    --covariates ${covariates_file} \
    --interaction ${interactions_file} \
    --mode cis_nominal`
The software reported TypeError when it met chr2:
for k, (phenotype, genotypes, genotype_range, phenotype_id) in enumerate(igc.generate_data(chrom=chrom, verbose=verbose), k+1):
TypeError: can only concatenate str (not "int") to str

Then I found that when I separated chromosome 2 genes from the phenotype bed file and ran it independently, the error disappeared. Could you please kindly explain the error?

**Comment by francois-a** [comment]
This is potentially because the BED file was not sorted correctly. Otherwise, this should be fixed in the latest version.
