### ISSUE TITLE
problematic variant

### ISSUE THREAD

**Issue by guandailu** [broadinstitute/tensorqtl#86]
Code:
python3 -m tensorqtl Redjunglefowl_Leghorn Redjunglefowl_Leghorn.bed.gz test --covariates Redjunglefowl_Leghorn.cov --interaction Redjunglefowl_Leghorn.breeds.txt --mode cis_nominal  --warn_monomorphic --load_split --maf_threshold 0.05  --maf_threshold_interaction 0.05

Log:
[Jan 23 11:12:18] Running TensorQTL: cis-QTL mapping
  * WARNING: using CPU!
  * reading phenotypes (Redjunglefowl_Leghorn.bed.gz)
  * reading covariates (Redjunglefowl_Leghorn.cov)
  * reading interaction term(s) (Redjunglefowl_Leghorn.breeds.txt)
Mapping files: 100%|██████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.39it/s]
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 124 samples
  * 1937 phenotypes
  * 15 covariates
  * 254824 variants
  * including 1 interaction term(s)
    * using 0.05 MAF threshold
  * checking phenotypes: 1937/1937
    ** dropping 9 phenotypes without variants in cis-window
  * Computing associations
    Mapping chromosome 1
    processing phenotype 8/1928Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dguan/.local/lib/python3.6/site-packages/tensorqtl/__main__.py", line 2, in <module>
    tensorqtl.main()
  File "/home/dguan/.local/lib/python3.6/site-packages/tensorqtl/tensorqtl.py", line 149, in main
    output_dir=args.output_dir, write_top=True, write_stats=not args.best_only, logger=logger, verbose=True)
  File "/home/dguan/.local/lib/python3.6/site-packages/tensorqtl/cis.py", line 280, in map_nominal
    variant_ids=variant_ids)
  File "/home/dguan/.local/lib/python3.6/site-packages/tensorqtl/core.py", line 196, in calculate_interaction_nominal
    Xinv = torch.matmul(torch.transpose(X_t, 1, 2), X_t).inverse() # ng x (1+2*ni) x (1+2*ni)
RuntimeError: inverse_cpu: For batch 41: U(3,3) is zero, singular U.
    Likely problematic variant: rs315903898 

Many variants have this issue?

**Comment by francois-a** [comment]
Can you provide more details about your inputs? This error occurs if there is colinearity between the genotypes and interactions.
