### ISSUE TITLE
Allele frequency reported in nominal cis-mQTLs output

### ISSUE THREAD

**Issue by ariadnacilleros** [broadinstitute/tensorqtl#88]
Hi, 

I have run two analyses with the nominal cis-QTL approach. In both analyses, I used the same input files, except for the covariates file, which was different. But in the outputs from the analyses, different AF has been reported. In one of them, all the AF correspond to the MAF, and in the other, not always. So, I was wondering, if the effect allele considered is the one corresponding to the AF column, or if it is the ALT from the bim file (PLINK)? And also, how this could happen if both analyses have been run with the same PLINK set files? Thank you so much for the tool. 

Best regards, 

Ariadna.

**Comment by francois-a** [comment]
Hi, sorry for not responding to this — the effect is always the ALT allele. I you see discrepancies it's likely due to an allele flip in PLINK 1.9 when the `--keep-allele-order ` flag is not used.
