### ISSUE TITLE
TensorQTL for non-genomic data

### ISSUE THREAD

**Issue by SynaSpike** [broadinstitute/tensorqtl#89]
Dear team,

I want to start by thanking you for your excellent work on TensorQTL. I have a question regarding the use of TensorQTL for linking non-genomic data. Specifically, I have a phenotype dataset that consists of clusters (rows) and patient IDs (columns) with their respective counts. I'm wondering if it's possible to link these counts to SNPs without referring to concept as genomic positions (i.e., cis or trans).

I appreciate any guidance or suggestions you can provide. Thank you.

**Comment by francois-a** [comment]
I'm not sure I fully understand the question, but in general, the 'genotypes' can be any type of data. `tensorqtl.genotypeio.load_genotypes` supports a range of input formats. The only genotype-specific feature is imputation of missing genotypes (coded as -1), which may not apply in other cases. As long as the inputs don't contain missing values, this shouldn't be a problem. If these phenotypes are not linked to positional information, you can use `--mode trans` to compute the associations.

**Comment by SynaSpike** [comment]
Right ! I have tried it and it works perfectly fine thanks !! 
I was wondering if there is any way to investigate for interaction terms in the trans mode ?

**Comment by francois-a** [comment]
Yes, interactions are supported in trans mode (but currently only a single term) .

**Comment by SynaSpike** [comment]
Right thanks for your help !
