### ISSUE TITLE
Limit the number of multi-threading

### ISSUE THREAD

**Issue by anglixue** [broadinstitute/tensorqtl#91]
Hi François,

I wonder if there is any flag to limit the number of multi-thread computing in the main script like `cis.map_cis()`?

It seems currently it has no cap on that and the software will use all the available subprocessors.

Thanks very much for your help!

Cheers,
Angli

**Comment by francois-a** [comment]
Hi, at what point during execution do you see this, and how many cores are being used? The genotype loader will use up to 6 threads by default (currently hard-coded, but I can make this an option).

**Comment by daniel-hui** [comment]
Hi, I'm wondering if there is a way to limit the threads now? For recent runs tensorQTL seems to use all available cores. I looked through --help and Issues and didn't see an option. Thanks.

Daniel
