### ISSUE TITLE
Question - genetic data from related

### ISSUE THREAD

**Issue by dpelegri** [broadinstitute/tensorqtl#92]
Hi,

I wonder if TensorQTL allows to analyse genetic data from related individuals (ie. mother-child GWAS data): 

> gene expression = SNP-mother + SNP-child + covariates

Or if there is any way to modify the code to fit it.
Thank you
Dolors

**Comment by francois-a** [comment]
A future version may support this, but currently you'll need to restrict the dataset to unrelated individuals.
