### ISSUE TITLE
tensorqtl 1.0.8 not available on pip

### ISSUE THREAD

**Issue by Jiacheng0007** [broadinstitute/tensorqtl#94]
Hi,

I'm reaching out to discuss an observation I've made, specifically in reference to the use of 'tensorqlt' version 1.0.8.

I noticed it appears to be unavailable upon attempting to retrieve this version through pip.
https://pypi.org/project/tensorqtl/

Thank you,
Jiacheng

**Comment by francois-a** [comment]
It's available now.
