### ISSUE TITLE
way to specify technical or biological replicates?

### ISSUE THREAD

**Issue by gpertea** [broadinstitute/tensorqtl#96]
Is there a way to specify multiple samples (phenotype data), for the same subject? I.e. technical or biological replicates for the same individual (or time points data). 
I could not find a documentation about this, and I assume the sample IDs in the phenotype (expression) BED files must be unique,  and it seems they must exactly match the genotype IDs. 

Or maybe there is a way to inform tensorQTL about a mapping between phenotype sample IDs and the genotype IDs?

**Comment by francois-a** [comment]
A future version may support this, but the current model does not. You'll need to select a single sample per individual.
